### ISSUE TITLE
Cross plugin dependencies (cont'd): NoClassDefFoundError: Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#162]
When the S3 and WebDAV plugin are installed and the daemon is started like this: `sy daemon -d`, the following exception is thrown for each managed folder:

```
Exception in thread "WatchOpT/Shared" java.lang.NoClassDefFoundError: Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory
    at org.syncany.plugins.webdav.WebdavTransferManager.initSsl(WebdavTransferManager.java:468)
    at org.syncany.plugins.webdav.WebdavTransferManager.connect(WebdavTransferManager.java:101)
    at org.syncany.plugins.webdav.WebdavTransferManager.list(WebdavTransferManager.java:193)
    at org.syncany.plugins.transfer.RetriableTransferManager$7.execute(RetriableTransferManager.java:126)
    at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:185)
    at org.syncany.plugins.transfer.RetriableTransferManager.list(RetriableTransferManager.java:123)
    at org.syncany.operations.ls_remote.LsRemoteOperation.listUnknownRemoteDatabases(LsRemoteOperation.java:86)
    at org.syncany.operations.ls_remote.LsRemoteOperation.execute(LsRemoteOperation.java:73)
    at org.syncany.operations.down.DownOperation.listUnknownRemoteDatabases(DownOperation.java:210)
    at org.syncany.operations.down.DownOperation.checkPreconditions(DownOperation.java:185)
    at org.syncany.operations.down.DownOperation.execute(DownOperation.java:137)
    at org.syncany.operations.watch.WatchOperation.runSync(WatchOperation.java:246)
    at org.syncany.operations.watch.WatchOperation.execute(WatchOperation.java:145)
    at org.syncany.operations.daemon.WatchOperationRunner$1.run(WatchOperationRunner.java:63)
    at java.lang.Thread.run(Thread.java:745)
```

The reason is that both plugin JARs contain the same dependency to Apache HTTP Components 4.3.1, and both plugin JARs contain all class files of this dependency.

This issue relates to (and is a continuation of) issue #154.

**Comment by aa992131860aa** [comment]
you haven't jar
