### ISSUE TITLE
Support for 200k+ files; find bottlenecks and test with many files

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#195]
As we saw in #115, Syncany currently has a few issues with large amounts of files. It can handle 200k+ files, but apparently has issues with 400k+ files.

This issue's purpose is to 
- [ ] Test performance with many files
- [ ] Find bottlenecks that make processing slow (read stuff to memory)
- [ ] Find memory leaks to free up memory for important stuff (dedup, et al); *see #382*

Let us know what your experiences are with many files, or ask on IRC (#syncany on Freenode).

**Comment by binwiederhier** [comment]
I've tested an SFTP repo with 200k files and the upload went fine. The indexing needs a lot of CPU (one core), but it worked in an acceptable amount of time for that number of files. I was using the GUI, but I'm sure the CLI would've worked just fine too.

The 'down' process was a bit more troubling. 

**First attempt:** In the GUI, the download went fine: The database files (29 MB) were downloaded and loaded into memory. That obviously needs a lot of memory and takes a bit of time, but it worked. The `ApplyOperation` then didn't go so well. It ran on 100% CPU on all 4 of my cores. Files were created -- about 67k of them. Then everything slowed down/stopped, and threads were running in different speeds/time zones (as this log excerpt shows). *Look at the timestamps!!*:

```
3-1-15 18:35:14.442 | RecursiveWatche | FsSettleTim/Ma | INFO : Registering new folders at watch service ...
3-1-15 18:34:53.256 | NotificationLis | NotifyThread   | INFO : Waiting for incoming message (10000 ms) ...
3-1-15 18:35:17.386 | NotificationLis | NotifyThread   | INFO : Waiting for incoming message (10000 ms) ...
3-1-15 18:35:11.642 | WatchOperation  | WR/Office      | INFO : RUNNING SYNC ...
3-1-15 18:35:08.696 | AppIndicatorTra | Thread-2       | INFO : Sending message: <updateTrayIconGuiInternalEvent>
   <filename>tray-syncing1.png</filename>
</updateTrayIconGuiInternalEvent>
3-1-15 18:35:06.145 | AppIndicatorTra | Thread-3       | INFO : Python Input Stream : Received request: <updateTrayIconGuiInternalEvent>
3-1-15 18:39:35.539 | AppIndicatorTra | Thread-3       | INFO : Python Input Stream :    <filename>tray-syncing6.png</filename>
3-1-15 18:39:42.488 | AppIndicatorTra | Thread-3       | INFO : Python Input Stream : </updateTrayIconGuiInternalEvent>
3-1-15 18:35:01.689 | RecursiveWatche | FsSettleTim/Ma | INFO : File system actions (on watched folders) settled. Updating watches ...
3-1-15 18:34:59.156 | Assembler       | WR/Many2       | INFO :      - Creating file 155589 to /home/pheckel/Syncany/Many2/.syncany/cache/temp-reconstructedFileVersion-8090200506976397536.tmp ...
3-1-15 18:39:42.488 | AppIndicatorTra | Thread-3       | INFO : Python Input Stream : Received request: <updateTrayIconGuiInternalEvent>
3-1-15 18:39:42.488 | AppIndicatorTra | Thread-3       | INFO : Python Input Stream :    <filename>tray-syncing1.png</filename>
3-1-15 18:39:42.488 | AppIndicatorTra | Thread-3       | INFO : Python Input Stream : </updateTrayIconGuiInternalEvent>
3-1-15 18:39:42.489 | FileSystemActio | WR/Many2       | INFO :      - Setting POSIX permissions: rw-r--r-- ...
3-1-15 18:39:42.489 | Assembler       | WR/Many2       | INFO :      - Creating file 15559 to /home/pheckel/Syncany/Many2/.syncany/cache/temp-reconstructedFileVersion-922502679134357873.tmp ...
3-1-15 18:34:59.156 | NotificationLis | NotifyThread   | INFO : Waiting for incoming message (10000 ms) ...
3-1-15 18:34:59.156 | NotificationLis | NotifyThread   | INFO : Waiting for incoming message (10000 ms) ...
3-1-15 18:39:50.532 | AppIndicatorTra | Thread-2       | INFO : Sending message: <updateTrayIconGuiInternalEvent>
   <filename>tray-syncing2.png</filename>
</updateTrayIconGuiInternalEvent>
3-1-15 18:37:57.892 | InternalEventBu | WR/Office      | INFO : Event bus 'LocalEventBus': Posting event WatchStartSyncExternalEvent (org.syncany.operations.daemon.messages.WatchStartSyncExternalEvent@12324cd8) ...

(NOTHING REMOVED HERE. Look a the time stamp gap!)

3-1-15 18:40:00.106 | FileSystemActio | WR/Many2       | INFO :      - Setting POSIX permissions: rw-r--r-- ...
3-1-15 18:40:00.106 | WebServer       | WR/Office      | INFO : Sending broadcast message to 1 websocket client(s)
3-1-15 18:40:00.106 | WebServer       | WR/Office      | INFO : Sending message to WebSocket13Channel[ No Receiver [] -- [] -- []]: <watchStartSyncExternalEvent>
   <root>/home/pheckel/Syncany/Office</root>
</watchStartSyncExternalEvent>
3-1-15 18:40:00.107 | Assembler       | WR/Many2       | INFO :      - Creating file 155590 to /home/pheckel/Syncany/Many2/.syncany/cache/temp-reconstructedFileVersion-8327406119209863847.tmp ...
3-1-15 18:36:29.167 | NotificationLis | NotifyThread   | INFO : Waiting for incoming message (10000 ms) ...
3-1-15 18:40:00.107 | FileSystemActio | WR/Many2       | INFO :      - Setting POSIX permissions: rw-r--r-- ...
3-1-15 18:35:53.358 | NotificationLis | NotifyThread   | INFO : Waiting for incoming message (10000 ms) ...
3-1-15 18:35:48.415 | SftpTransferMan | ActRenewTim    | INFO : SFTP: Renaming temp file /home/pheckel/Syncany/Repos/many/temp-action-down-JEBbnpRQuQcSFRFmDhLi-1420306490858 to file /home/pheckel/Syncany/Repos/many/actions/action-down-JEBbnpRQuQcSFRFmDhLi-1420306490858
...
```

**Second attempt:** After the GUI 'down' didn't work, I tried it with `sy down` manually. That worked better, because there were no other watches running, but it failed after creating 122k files during the `ApplyOperation`:

```
3-1-15 18:48:11.347 | Assembler       | main           | INFO :      - Creating file 29929 to /home/pheckel/Syncany/Many2/.syncany/cache/temp-reconstructedFileVersion-626807872228962518.tmp ...
3-1-15 18:48:11.348 | FileSystemActio | main           | INFO :      - Setting POSIX permissions: rw-r--r-- ...
3-1-15 18:48:14.036 | ActionFileHandl | ActRenewTim    | INFO : Scheduling action renewal task for every 2 minutes, for RemoteFile[name=action-down-JEBbnpRQuQcSFRFmDhLi-1420307172172] ...
3-1-15 18:48:24.088 | Assembler       | main           | INFO :      - Creating file 2993 to /home/pheckel/Syncany/Many2/.syncany/cache/temp-reconstructedFileVersion-7501750478226592115.tmp ...
3-1-15 18:48:24.088 | ActionFileHandl | ActRenewTim    | INFO : Uploading action file: RemoteFile[name=action-down-JEBbnpRQuQcSFRFmDhLi-1420307299697]
3-1-15 18:48:30.957 | SftpTransferMan | ActRenewTim    | INFO : SFTP: Uploading /tmp/syncany-action-161966444120102004.tmp to temp file /home/pheckel/Syncany/Repos/many/temp-action-down-JEBbnpRQuQcSFRFmDhLi-1420307299697
3-1-15 18:48:30.960 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DownCommand@6caf446 FAILED. 
java.lang.RuntimeException: java.sql.SQLException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.syncany.database.dao.FileContentSqlDao.getFileContentWithChunkChecksums(FileContentSqlDao.java:217)
	at org.syncany.database.dao.FileContentSqlDao.getFileContent(FileContentSqlDao.java:140)
	at org.syncany.database.SqlDatabase.getFileContent(SqlDatabase.java:330)
	at org.syncany.operations.Assembler.assembleToCache(Assembler.java:78)
	at org.syncany.operations.down.actions.FileCreatingFileSystemAction.assembleFileToCache(FileCreatingFileSystemAction.java:82)
	at org.syncany.operations.down.actions.FileCreatingFileSystemAction.createFile(FileCreatingFileSystemAction.java:74)
	at org.syncany.operations.down.actions.FileCreatingFileSystemAction.createFileFolderOrSymlink(FileCreatingFileSystemAction.java:38)
	at org.syncany.operations.down.actions.NewFileSystemAction.execute(NewFileSystemAction.java:42)
	at org.syncany.operations.down.ApplyChangesOperation.applyFileSystemActions(ApplyChangesOperation.java:194)
	at org.syncany.operations.down.ApplyChangesOperation.execute(ApplyChangesOperation.java:103)
	at org.syncany.operations.down.DownOperation.applyWinnersBranch(DownOperation.java:457)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:189)
	at org.syncany.Client.down(Client.java:125)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: java.sql.SQLException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at org.syncany.database.dao.AbstractSqlDao.getStatement(AbstractSqlDao.java:50)
	at org.syncany.database.dao.AbstractSqlDao.getStatement(AbstractSqlDao.java:46)
	at org.syncany.database.dao.FileContentSqlDao.getFileContentWithChunkChecksums(FileContentSqlDao.java:194)
	... 17 more
Caused by: org.hsqldb.HsqlException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.result.Result.newErrorResult(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 22 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.String.toUpperCase(String.java:2598)
	at org.hsqldb.Scanner.scanUndelimitedIdentifier(Unknown Source)
	at org.hsqldb.Scanner.scanIdentifierChain(Unknown Source)
	at org.hsqldb.Scanner.scanToken(Unknown Source)
	at org.hsqldb.Scanner.scanNext(Unknown Source)
	at org.hsqldb.ParserBase.read(Unknown Source)
	at org.hsqldb.ParserBase.readIfThis(Unknown Source)
	at org.hsqldb.ParserDQL.XreadSelect(Unknown Source)
	at org.hsqldb.ParserDQL.XreadQuerySpecification(Unknown Source)
	at org.hsqldb.ParserDQL.XreadSimpleTable(Unknown Source)
	at org.hsqldb.ParserDQL.XreadQueryPrimary(Unknown Source)
	at org.hsqldb.ParserDQL.XreadQueryTerm(Unknown Source)
	at org.hsqldb.ParserDQL.XreadQueryExpressionBody(Unknown Source)
	at org.hsqldb.ParserDQL.XreadQueryExpression(Unknown Source)
	at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source)
	at org.hsqldb.Session.compileStatement(Unknown Source)
	at org.hsqldb.StatementManager.compile(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at org.syncany.database.dao.AbstractSqlDao.getStatement(AbstractSqlDao.java:50)
	at org.syncany.database.dao.AbstractSqlDao.getStatement(AbstractSqlDao.java:46)
	at org.syncany.database.dao.FileContentSqlDao.getFileContentWithChunkChecksums(FileContentSqlDao.java:194)
	at org.syncany.database.dao.FileContentSqlDao.getFileContent(FileContentSqlDao.java:140)
	at org.syncany.database.SqlDatabase.getFileContent(SqlDatabase.java:330)
	at org.syncany.operations.Assembler.assembleToCache(Assembler.java:78)
	at org.syncany.operations.down.actions.FileCreatingFileSystemAction.assembleFileToCache(FileCreatingFileSystemAction.java:82)
	at org.syncany.operations.down.actions.FileCreatingFileSystemAction.createFile(FileCreatingFileSystemAction.java:74)
	at org.syncany.operations.down.actions.FileCreatingFileSystemAction.createFileFolderOrSymlink(FileCreatingFileSystemAction.java:38)
	at org.syncany.operations.down.actions.NewFileSystemAction.execute(NewFileSystemAction.java:42)
```

**Comment by binwiederhier** [comment]
Tested up+down today with v0.4.7-alpha. Works!

**Comment by ruipgpinheiro** [comment]
On a huge folder (57338 files and 8840 folders; 29GB), using v0.4.7-alpha, I still get random OutOfMemory errors during `sy down`. Either the heap space is exceeded, or the GC overhead limit, and syncany simply closes halfway through the sync.

I have never had `sy up` fail, but that might just be a coincidence.

So, assuming that #283 really belongs to this issue, this hasn't been completely fixed yet.

**Comment by ruipgpinheiro** [comment]
I attempted to `sy down` about 6 times, and it never completes successfuly for this folder, always with "GC Overhead limit exceeded" or "Heap space exceeded".

The last time, I saved what seems to be the important part of the log:

	29-12-15 1:39:00.543 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:00.605 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1175768,3681 operation 14987,62 txts 329787
	29-12-15 1:39:15.222 | DownOperation   | main           | INFO :   + Applying database version (CMWvHvSNqMWlvFDdYMwK144)
	29-12-15 1:39:15.222 | DownOperation   | main           | FINE :   + Contents: DatabaseVersion [header=CMWvHvSNqMWlvFDdYMwK/(CMWvHvSNqMWlvFDdYMwK144)/T=14498985
	15311, chunks=1173, multiChunks=13, fileContents=1123, fileHistories=3099]
	29-12-15 1:39:24.473 | DatabaseVersion | main           | SEVE : SQL Error:
	java.sql.BatchUpdateException: java.lang.OutOfMemoryError: GC overhead limit exceeded
			at org.hsqldb.jdbc.JDBCPreparedStatement.executeBatch(Unknown Source)
			at org.syncany.database.dao.ChunkSqlDao.writeChunks(ChunkSqlDao.java:69)
			at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:146)
			at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:108)
			at org.syncany.database.SqlDatabase.writeDatabaseVersion(SqlDatabase.java:201)
			at org.syncany.operations.down.DownOperation.persistDatabaseVersion(DownOperation.java:527)
			at org.syncany.operations.down.DownOperation.persistDatabaseVersions(DownOperation.java:514)
			at org.syncany.operations.down.DownOperation.applyChangesAndPersistDatabase(DownOperation.java:495)
			at org.syncany.operations.down.DownOperation.applyWinnersBranch(DownOperation.java:470)
			at org.syncany.operations.down.DownOperation.execute(DownOperation.java:190)
			at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
			at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
			at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
			at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
			at org.syncany.Syncany.main(Syncany.java:52)
	29-12-15 1:39:26.345 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:26.345 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1191999,3681 operation 16231,0 txts 334271
	29-12-15 1:39:26.485 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:26.485 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1213316,3681 operation 21317,0 txts 334271
	29-12-15 1:39:26.626 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:26.626 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1238248,3681 operation 24932,0 txts 334271
	29-12-15 1:39:26.735 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:26.751 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1263071,3697 operation 24823,16 txts 334271
	29-12-15 1:39:26.844 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 15
	29-12-15 1:39:26.844 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1288005,3712 operation 24934,15 txts 334271
	29-12-15 1:39:27.000 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:27.000 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1312946,3712 operation 24941,0 txts 334271
	29-12-15 1:39:27.094 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:27.109 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1337893,3727 operation 24947,15 txts 334271
	29-12-15 1:39:27.219 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:27.234 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1362884,3742 operation 24991,15 txts 334271
	29-12-15 1:39:27.343 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:27.343 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1387872,3742 operation 24988,0 txts 334271
	29-12-15 1:39:27.453 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:27.468 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1412755,3757 operation 24883,15 txts 334271
	29-12-15 1:39:27.546 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:27.546 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1437732,3757 operation 24977,0 txts 334271
	29-12-15 1:39:27.640 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:27.655 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1462621,3772 operation 24889,15 txts 334271
	29-12-15 1:39:27.749 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:27.749 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1487594,3772 operation 24973,0 txts 334271
	29-12-15 1:39:27.843 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:27.858 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1512556,3787 operation 24962,15 txts 334271
	29-12-15 1:39:27.936 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:27.952 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1537418,3803 operation 24862,16 txts 334271
	29-12-15 1:39:28.030 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:28.045 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1562276,3818 operation 24858,15 txts 334271
	29-12-15 1:39:28.155 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:28.155 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1587178,3818 operation 24902,0 txts 334271
	29-12-15 1:39:28.233 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:28.248 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1612013,3833 operation 24835,15 txts 334271
	29-12-15 1:39:28.326 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:28.342 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1636849,3849 operation 24836,16 txts 334271
	29-12-15 1:39:28.451 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:28.451 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1661583,3849 operation 24734,0 txts 334271
	29-12-15 1:39:28.529 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:28.529 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1686558,3849 operation 24975,0 txts 334271
	29-12-15 1:39:28.654 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:28.654 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1711480,3849 operation 24922,0 txts 334271
	29-12-15 1:39:28.763 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:28.779 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1736230,3865 operation 24750,16 txts 334271
	29-12-15 1:39:28.903 | hsqldb.db.HSQLD | main           | FINE : copyShadow [size, time] 16396 0
	29-12-15 1:39:28.903 | hsqldb.db.HSQLD | main           | FINE : cache save rows [count,time] totals 1761129,3865 operation 24899,0 txts 334271
	29-12-15 1:39:29.200 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DownCommand@7225790e FAILED.
	java.lang.RuntimeException: Cannot persist database.
			at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:118)
			at org.syncany.database.SqlDatabase.writeDatabaseVersion(SqlDatabase.java:201)
			at org.syncany.operations.down.DownOperation.persistDatabaseVersion(DownOperation.java:527)
			at org.syncany.operations.down.DownOperation.persistDatabaseVersions(DownOperation.java:514)
			at org.syncany.operations.down.DownOperation.applyChangesAndPersistDatabase(DownOperation.java:495)
			at org.syncany.operations.down.DownOperation.applyWinnersBranch(DownOperation.java:470)
			at org.syncany.operations.down.DownOperation.execute(DownOperation.java:190)
			at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
			at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
			at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
			at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
			at org.syncany.Syncany.main(Syncany.java:52)
	Caused by: java.sql.BatchUpdateException: java.lang.OutOfMemoryError: GC overhead limit exceeded
			at org.hsqldb.jdbc.JDBCPreparedStatement.executeBatch(Unknown Source)
			at org.syncany.database.dao.ChunkSqlDao.writeChunks(ChunkSqlDao.java:69)
			at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:146)
			at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:108)
			... 11 more
	Error: Cannot persist database.
		   Refer to help page using '--help'.

**Comment by pimotte** [comment]
Yep. I'm going to reopen this for a bit, since I missed out on post-cleanup down operations. 

For your particular case, if you want to you can configure the maxMemory property to be larger. We only take 512MB by default.

**Comment by ruipgpinheiro** [comment]
>For your particular case, if you want to you can configure the maxMemory property to be larger. We only take 512MB by default. 

Changed my maxMemory property to `6G`, but it still doesn't work, failing with "GC overhead limit exceeded" exactly like my previous log.
