### ISSUE TITLE
Parallelize 'index' and 'upload' process w/ smart cache handling

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#257]
As of today, the index and upload process are executed subsequently -- meaning that the cache will fill up to max. the size of the local folder. If the local folder size is 1 GB, the cache size will also grow to <= 1 GB (probably a lot less, but for random data it'll be 1 GB). In this example, the temporary disk usage will be <= 2 GB. Only after the 'sy up' was successful, the cache is cleared to `cacheKeepBytes`. In short:
1. Local dir is 1 GB
2. `Indexer` fills cache to <= 1 GB (**disk usage <= 2 GB**)
3. `Uploader` uploads multichunks in cache
4. Cache is reduced to `cacheKeepBytes` (default: 500 MB)

---

It is desirable to parallelize `Indexer` and `Uploader` and make them both cache-aware -- meaning that `Indexer` and `Uploader` run in different threads and "produce" and "consume" items in the cache: The `Indexer` produces new multichunks and puts it in the cache. When the cache is full (i.e. it reaches a new parameter `cacheMaxSize`), it waits/pauses until the `Uploader` has consumed (= uploaded) one or many multichunks.

This is obviously not easy, but also a very exciting feature request. Volunteers?
Thanks to _b8e5n_ for mentioning it on IRC.

**Comment by binwiederhier** [comment]
IMHO, this could be easily fixed now, because we split the uploads into smaller batches. If we cleared the cache after every batch, we'd be golden (except for files > 500MB, there we'd have the same problem). 

@pimotte @cr0 Thoughts?

**Comment by pimotte** [comment]
Agree. This could certainly be done and it shouldn't take much.

**Comment by lvicainne** [comment]
Hello.
I think this feature (or maybe a bug because it is a side effect) would be really useful.
I wanted to use Syncanyfor backing up a directory in my 50Gb partition.
However, as other people, I would like to backup up a directory of 15Gb and it is remaining only 10Gb 
I have another 50Gb partition free on my server, so I will have to chosse for the moment another software.

In case you need to debug (French version) :

F:\CHARLEMAGNE>sy up
Indexed 47412/51297 file(s)...java.io.IOException: Espace insuffisant sur le dis
que
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(Unknown Source)
        at org.bouncycastle.crypto.io.CipherOutputStream.write(Unknown Source)
        at org.syncany.crypto.MultiCipherOutputStream.write(MultiCipherOutputStr
eam.java:105)
        at java.util.zip.DeflaterOutputStream.deflate(Unknown Source)
        at java.util.zip.DeflaterOutputStream.write(Unknown Source)
        at java.util.zip.GZIPOutputStream.write(Unknown Source)
        at java.util.zip.DeflaterOutputStream.deflate(Unknown Source)
        at java.util.zip.DeflaterOutputStream.write(Unknown Source)
        at java.util.zip.ZipOutputStream.write(Unknown Source)
        at org.syncany.chunk.ZipMultiChunk.write(ZipMultiChunk.java:73)
        at org.syncany.chunk.Deduper.deduplicate(Deduper.java:127)
        at org.syncany.operations.up.Indexer.indexWithNewFiles(Indexer.java:144)

        at org.syncany.operations.up.Indexer.index(Indexer.java:116)
        at org.syncany.operations.up.AsyncIndexer.run(AsyncIndexer.java:47)
        at java.lang.Thread.run(Unknown Source)
java.util.logging.ErrorManager: 2
java.io.IOException: Espace insuffisant sur le disque
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(Unknown Source)
        at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.io.BufferedOutputStream.flush(Unknown Source)
        at java.util.logging.FileHandler$MeteredStream.flush(Unknown Source)
        at sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
        at sun.nio.cs.StreamEncoder.flush(Unknown Source)
        at java.io.OutputStreamWriter.flush(Unknown Source)
        at java.util.logging.StreamHandler.flush(Unknown Source)
        at java.util.logging.FileHandler.publish(Unknown Source)
        at java.util.logging.Logger.log(Unknown Source)
        at java.util.logging.Logger.doLog(Unknown Source)
        at java.util.logging.Logger.logp(Unknown Source)
        at org.hsqldb.lib.FrameworkLogger.privlog(Unknown Source)
        at org.hsqldb.lib.FrameworkLogger.warning(Unknown Source)
        at org.hsqldb.persist.Logger.logWarningEvent(Unknown Source)
        at org.hsqldb.TransactionManagerCommon.persistCommit(Unknown Source)
        at org.hsqldb.TransactionManager2PL.commitTransaction(Unknown Source)
        at org.hsqldb.Session.commit(Unknown Source)
        at org.hsqldb.jdbc.JDBCConnection.commit(Unknown Source)
        at org.syncany.database.dao.DatabaseVersionSqlDao.removeDirtyDatabaseVer
sions(DatabaseVersionSqlDao.java:221)
        at org.syncany.database.SqlDatabase.removeDirtyDatabaseVersions(SqlDatab
ase.java:213)
        at org.syncany.operations.up.UpOperation.executeTransactions(UpOperation
.java:319)
        at org.syncany.operations.up.UpOperation.execute(UpOperation.java:168)
        at org.syncany.cli.UpCommand.execute(UpCommand.java:56)
        at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:3
92)
        at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:3
82)
        at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
        at org.syncany.Syncany.main(Syncany.java:52)
Error: F:\CHARLEMAGNE\.syncany\cache\database-tZDwjrVRkprrAPvjrPKd-0000000103 (E
space insuffisant sur le disque)
       Refer to help page using '--help'.

**Comment by Akuukis** [comment]
I also run sync without enough free space, and  got a bit different stack trace. I wonder, why 3437 and 2338 doesn't match?
```
$USER@$HOST:~/sync$ sy up
Indexed 3134/3437 file(s)...java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:345)
        at org.bouncycastle.crypto.io.CipherOutputStream.write(Unknown Source)
        at org.syncany.crypto.MultiCipherOutputStream.write(MultiCipherOutputStream.java:105)
        at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
        at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
        at java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:146)
        at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
        at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
        at java.util.zip.ZipOutputStream.write(ZipOutputStream.java:314)
        at org.syncany.chunk.ZipMultiChunk.write(ZipMultiChunk.java:73)
        at org.syncany.chunk.Deduper.deduplicate(Deduper.java:127)
        at org.syncany.operations.up.Indexer.indexWithNewFiles(Indexer.java:144)
        at org.syncany.operations.up.Indexer.index(Indexer.java:116)
        at org.syncany.operations.up.AsyncIndexer.run(AsyncIndexer.java:47)
        at java.lang.Thread.run(Thread.java:745)
^C$USER@$HOST:~/sync$ ^C
$USER@$HOST:~/sync$ sy up
Indexed 1926/2338 file(s)... 
```
