### ISSUE TITLE
Sy Gui not working with Kubuntu/KF5

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#275]
_(Copied issue from https://github.com/syncany/syncany-plugin-gui/issues/2)_

Running Kubuntu 14.10 with KF5 (Plasma 5), and have installed .deb plus other dependencies mentioned that weren't installed by the .deb dependencies (python-appindicator, python-pip, websocket-client).

However, no gui is shown and no message is shown on the commandline.

Is this a missing dependency, a lack of support in KDE, or in KDE plasma 5 in particular?

**Comment by jaltek** [comment]
Since I upgraded my system to openSUSE Tumbleweed with KDE Plasma 5.3 I have the same problem.
I also installed the libappindicator libraries which doesn't help either.
By using ```sy gui --tray=APPINDICATOR ``` syncany loops over this messages block

```
3-9-15 12:25:34.777 | AppIndicatorTra | PyAppInd       | INFO : Starting Python logger thread for 'PySTDIN' ...
3-9-15 12:25:34.778 | AppIndicatorTra | PyAppInd       | INFO : Starting Python logger thread for 'PySTDERR' ...
3-9-15 12:25:34.780 | AppIndicatorTra | PyAppInd       | INFO : Python process started after crash (!): Waiting a bit, then sending list watches request ...
3-9-15 12:25:34.822 | org.xnio.nio.se | XNIO-1 I/O-3   | TRAC : Selected on sun.nio.ch.EPollSelectorImpl@c80e5e1
3-9-15 12:25:34.822 | org.xnio.nio.se | XNIO-1 I/O-3   | TRAC : Selected key sun.nio.ch.SelectionKeyImpl@14d3bc22 for sun.nio.ch.ServerSocketChannelImpl[/127.0.0.1:51601]
3-9-15 12:25:34.823 | org.xnio.listen | XNIO-1 I/O-3   | TRAC : Invoking listener Accepting listener for io.undertow.server.protocol.http.HttpOpenListener@395d8709 on channel TCP server (NIO) <33c2f8e>
3-9-15 12:25:34.823 | org.xnio.nio.se | XNIO-1 I/O-4   | TRAC : Selected on sun.nio.ch.EPollSelectorImpl@6b55bfeb
3-9-15 12:25:34.823 | org.xnio.nio    | XNIO-1 I/O-4   | TRAC : Running task org.xnio.nio.NioTcpServerHandle$4@62c31f53
3-9-15 12:25:34.823 | org.xnio.listen | XNIO-1 I/O-3   | TRAC : Invoking listener io.undertow.server.protocol.http.HttpOpenListener@395d8709 on channel org.xnio.nio.NioSocketStreamConnection@2bb9dcc4
3-9-15 12:25:34.823 | org.xnio.nio.se | XNIO-1 I/O-4   | TRAC : Beginning select on sun.nio.ch.EPollSelectorImpl@6b55bfeb
3-9-15 12:25:34.823 | io.undertow.req | XNIO-1 I/O-3   | TRAC : Opened connection with /127.0.0.1:50475
3-9-15 12:25:34.823 | org.xnio.nio.se | XNIO-1 I/O-3   | TRAC : Beginning select on sun.nio.ch.EPollSelectorImpl@c80e5e1
3-9-15 12:25:34.824 | io.undertow.ser | XNIO-1 task-6  | TRAC : Starting to write response for HttpServerExchange{ GET /api/res/tray.py}
3-9-15 12:25:34.824 | org.xnio.nio.se | XNIO-1 I/O-3   | TRAC : Selected on sun.nio.ch.EPollSelectorImpl@c80e5e1
3-9-15 12:25:34.824 | org.xnio.nio.se | XNIO-1 I/O-3   | TRAC : Beginning select on sun.nio.ch.EPollSelectorImpl@c80e5e1 (with timeout)
3-9-15 12:25:34.825 | org.xnio.safe-c | XNIO-1 task-6  | TRAC : Closing resource sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@351a8d7a
3-9-15 12:25:34.825 | org.xnio.safe-c | XNIO-1 task-6  | TRAC : Closing resource io.undertow.server.protocol.http.HttpServerConnection@701805bd
3-9-15 12:25:34.825 | org.xnio.nio    | XNIO-1 task-6  | TRAC : Cancelling key sun.nio.ch.SelectionKeyImpl@714af977 of java.nio.channels.SocketChannel[connected oshut local=/127.0.0.1:51601 remote=/127.0.0.1:50475] (other thread)
3-9-15 12:25:34.825 | org.xnio.listen | XNIO-1 task-6  | TRAC : Invoking listener io.undertow.server.AbstractServerConnection$CloseSetter@58626f02 on channel org.xnio.nio.NioSocketStreamConnection@2bb9dcc4
3-9-15 12:25:34.825 | org.xnio.nio.se | XNIO-1 I/O-3   | TRAC : Selected on sun.nio.ch.EPollSelectorImpl@c80e5e1
3-9-15 12:25:34.826 | org.xnio.nio    | XNIO-1 I/O-3   | TRAC : Running task org.xnio.nio.NioTcpServerHandle$1@196365c4
3-9-15 12:25:34.826 | org.xnio.nio.se | XNIO-1 I/O-3   | TRAC : Beginning select on sun.nio.ch.EPollSelectorImpl@c80e5e1 (with timeout)
3-9-15 12:25:34.927 | AppIndicatorTra | PySTDERR       | INFO : Python Error Stream: Traceback (most recent call last):
3-9-15 12:25:34.927 | AppIndicatorTra | PySTDERR       | INFO : Python Error Stream:   File "<string>", line 1, in <module>
3-9-15 12:25:34.927 | AppIndicatorTra | PySTDERR       | INFO : Python Error Stream:   File "<string>", line 32, in <module>
3-9-15 12:25:34.927 | AppIndicatorTra | PySTDERR       | INFO : Python Error Stream: ImportError: No module named websocket
3-9-15 12:25:35.001 | org.xnio.nio.se | XNIO-1 I/O-3   | TRAC : Selected on sun.nio.ch.EPollSelectorImpl@c80e5e1
3-9-15 12:25:35.001 | org.xnio.nio    | XNIO-1 I/O-3   | TRAC : Running task io.undertow.util.DateUtils$2@5381fae0
3-9-15 12:25:35.001 | org.xnio.nio.se | XNIO-1 I/O-3   | TRAC : Beginning select on sun.nio.ch.EPollSelectorImpl@c80e5e1
3-9-15 12:25:39.780 | InternalEventBu | PyAppInd       | INFO : Event bus 'GuiEventBus': Posting event ListWatchesManagementRequest (org.syncany.operations.daemon.messages.ListWatchesManagementRequest@c2d8ef6) ...
3-9-15 12:25:39.781 | InternalEventBu | PyAppInd       | INFO : Event bus 'LocalEventBus': Posting event ListWatchesManagementRequest (org.syncany.operations.daemon.messages.ListWatchesManagementRequest@c2d8ef6) ...
3-9-15 12:25:39.781 | InternalEventBu | PyAppInd       | INFO : Event bus 'LocalEventBus': Posting event ListWatchesManagementResponse (org.syncany.operations.daemon.messages.ListWatchesManagementResponse@16aff048) ...
3-9-15 12:25:39.781 | WatchServer     | PyAppInd       | INFO : Received org.syncany.operations.daemon.messages.ListWatchesManagementRequest@c2d8ef6
3-9-15 12:25:39.781 | WatchServer     | PyAppInd       | FINE : No handler found for management request class class org.syncany.operations.daemon.messages.ListWatchesManagementRequest. Ignoring.
3-9-15 12:25:39.781 | InternalEventBu | PyAppInd       | INFO : Event bus 'GuiEventBus': Posting event ListWatchesManagementResponse (org.syncany.operations.daemon.messages.ListWatchesManagementResponse@16aff048) ...
3-9-15 12:25:39.781 | WebServer       | PyAppInd       | WARN : Cannot send message, because request ID in response is unknown or timed out.org.syncany.operations.daemon.messages.ListWatchesManagementResponse@16aff048
3-9-15 12:25:39.781 | TrayIcon        | PyAppInd       | FINE : List watches response recevied: 0 watch(es)
3-9-15 12:25:39.781 | TrayIcon        | PyAppInd       | FINE : Resetting sync status for clients.
3-9-15 12:25:39.781 | TrayIcon        | PyAppInd       | FINE : Syncing image: Setting to image TRAY_IN_SYNC
3-9-15 12:25:39.781 | AppIndicatorTra | PyAppInd       | INFO : Python process started. Waiting indefinitely (or until it crashes :-/) ...
3-9-15 12:25:39.781 | AppIndicatorTra | PyAppInd       | INFO : Python process crashed. Waiting a bit before restart.
```

If you need any further debug logs or information let me know.
