### ISSUE TITLE
Swift plugin bug.

### ISSUE THREAD

**Issue by gudron** [syncany/syncany#276]
# Prepare environment
```
➜  .storages  mkdir selectel_swift_test
➜  .storages  mkdir rackspace_swift_test
➜  .storages  touch {rackspace,selectel}_swift_test/testfile
➜  .storages  echo "hello, this is first test file" > {rackspace,selectel}_swift_test/testfile
➜  .storages  mkdir {rackspace,selectel}_swift_test/testdir
➜  .storages  touch {rackspace,selectel}_swift_test/testdir/testfile2
➜  .storages  echo "hello, this is SECOND test file" > {rackspace,selectel}_swift_test/testdir/testfile2
```
First test on [selectel](http://selectel.com/services/cloud-storage/#software) storage
```
➜  .storages  cd selectel_swift_test
➜  selectel_swift_test  sy init        
Choose a storage plugin. Available plugins are: ftp, local, swift
Plugin: swift

Connection details for swift connection:
- Url to authenticate at the Swift cluster: https://auth.selcdn.ru
- Username: 15814_syncanytestusr
- Password (not displayed): 
- Target container to use: test_container

The password is used to encrypt data on the remote storage.
Choose wisely!

Password (min. 10 chars): 
Confirm: 

Creating master key from password (this might take a while) ...

Repository created, and local folder initialized. To share the same repository
with others, you can share this link:

   syncany://2/4caUTYg7iXvgNr1yApY31au...

This link is encrypted with the given password, so you can safely share it.
using unsecure communication (chat, e-mail, etc.)

WARNING: The link contains the details of your repo connection which typically
         consist of usernames/password of the connection (e.g. FTP user/pass).
```
# Begin synchronization
Ok. all is well. now - upload files on storage.
```
➜  selectel_swift_test  sy -d up 
debug
Application version: 0.2.0-alpha
25-11-14 14:31:50.764 | CommandLineClie | main           | INFO : Application version: 0.2.0-alpha
25-11-14 14:31:50.770 | PidFileUtil     | main           | INFO : isProcessRunningUnixLike(17904) returned 0, process running = true
25-11-14 14:31:50.772 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Registering StatusCommand (org.syncany.cli.StatusCommand@3cc710d1) ...
25-11-14 14:31:50.783 | org.syncany.plu | main           | FINE : Validating required fields
25-11-14 14:31:52.013 | org.syncany.plu | main           | FINE : Validating required fields
25-11-14 14:31:52.456 | DatabaseConnect | main           | INFO : Loading database driver org.hsqldb.jdbcDriver ...
25-11-14 14:31:52.759 | hsqldb.db.HSQLD | main           | INFO : Checkpoint start
25-11-14 14:31:52.760 | hsqldb.db.HSQLD | main           | INFO : checkpointClose start
25-11-14 14:31:52.837 | hsqldb.db.HSQLD | main           | FINE : log close size: 0
25-11-14 14:31:52.863 | hsqldb.db.HSQLD | main           | INFO : checkpointClose end
25-11-14 14:31:52.865 | hsqldb.db.HSQLD | main           | INFO : Checkpoint end - txts: 1
25-11-14 14:31:52.934 | DatabaseConnect | main           | INFO : Database has no tables. Creating tables from create.all.sql
25-11-14 14:31:52.937 | SqlRunner       | main           | INFO : SQL (comment): -- Tables
25-11-14 14:31:52.938 | SqlRunner       | main           | INFO : SQL:  CREATE CACHED TABLE databaseversion ( id int NOT NULL IDENTITY, type varchar(45) NOT NULL, status varchar(45) NOT NULL, localtime datetime NOT NULL, client varchar(45) NOT NULL, vectorclock_serialized varchar(1024) NOT NULL, UNIQUE (vectorclock_serialized) ); 
25-11-14 14:31:52.965 | SqlRunner       | main           | INFO : SQL:  CREATE CACHED TABLE chunk ( checksum varchar(40) NOT NULL, databaseversion_id int NOT NULL, size bigint NOT NULL, PRIMARY KEY (checksum), FOREIGN KEY (databaseversion_id) REFERENCES databaseversion (id) ON DELETE NO ACTION ON UPDATE NO ACTION ); 
25-11-14 14:31:52.990 | SqlRunner       | main           | INFO : SQL:  CREATE CACHED TABLE databaseversion_vectorclock ( databaseversion_id int NOT NULL, client varchar(45) NOT NULL, logicaltime int NOT NULL, PRIMARY KEY (databaseversion_id, client), FOREIGN KEY (databaseversion_id) REFERENCES databaseversion (id) ON DELETE NO ACTION ON UPDATE NO ACTION ); 
25-11-14 14:31:53.015 | SqlRunner       | main           | INFO : SQL:  CREATE CACHED TABLE filecontent ( checksum varchar(40) NOT NULL, databaseversion_id int NOT NULL, size bigint NOT NULL, PRIMARY KEY (checksum), FOREIGN KEY (databaseversion_id) REFERENCES databaseversion (id) ON DELETE NO ACTION ON UPDATE NO ACTION ); 
25-11-14 14:31:53.040 | SqlRunner       | main           | INFO : SQL:  CREATE CACHED TABLE filecontent_chunk ( filecontent_checksum varchar(40) NOT NULL, chunk_checksum varchar(40) NOT NULL, num int NOT NULL, PRIMARY KEY (filecontent_checksum, chunk_checksum, num), FOREIGN KEY (filecontent_checksum) REFERENCES filecontent (checksum) ON DELETE NO ACTION ON UPDATE NO ACTION, FOREIGN KEY (chunk_checksum) REFERENCES chunk (checksum) ON DELETE NO ACTION ON UPDATE NO ACTION ); 
25-11-14 14:31:53.065 | SqlRunner       | main           | INFO : SQL:  CREATE CACHED TABLE filehistory ( id varchar(40) NOT NULL, databaseversion_id int NOT NULL, PRIMARY KEY (id, databaseversion_id), FOREIGN KEY (databaseversion_id) REFERENCES databaseversion (id) ON DELETE NO ACTION ON UPDATE NO ACTION ); 
25-11-14 14:31:53.091 | SqlRunner       | main           | INFO : SQL:  CREATE CACHED TABLE fileversion ( filehistory_id varchar(40) NOT NULL, version int NOT NULL, databaseversion_id int NOT NULL, path varchar(1024) NOT NULL, type varchar(45) NOT NULL, status varchar(45) NOT NULL, size bigint NOT NULL, lastmodified datetime NOT NULL, linktarget varchar(1024), filecontent_checksum varchar(40) DEFAULT NULL, updated datetime NOT NULL, posixperms varchar(45) DEFAULT NULL, dosattrs varchar(45) DEFAULT NULL, PRIMARY KEY (filehistory_id, version, databaseversion_id), FOREIGN KEY (filehistory_id, databaseversion_id) REFERENCES filehistory (id, databaseversion_id) ON DELETE NO ACTION ON UPDATE NO ACTION, FOREIGN KEY (filecontent_checksum) REFERENCES filecontent (checksum) ON DELETE NO ACTION ON UPDATE NO ACTION ); 
25-11-14 14:31:53.124 | SqlRunner       | main           | INFO : SQL:  CREATE CACHED TABLE fileversion_purge ( filehistory_id varchar(40) NOT NULL, fileversion_maxpurgeversion int NOT NULL, databaseversion_id int NOT NULL, PRIMARY KEY (filehistory_id, fileversion_maxpurgeversion, databaseversion_id) ); 
25-11-14 14:31:53.149 | SqlRunner       | main           | INFO : SQL:  CREATE CACHED TABLE multichunk ( id varchar(40) NOT NULL, databaseversion_id int NOT NULL, size bigint NOT NULL, PRIMARY KEY (id), FOREIGN KEY (databaseversion_id) REFERENCES databaseversion (id) ON DELETE NO ACTION ON UPDATE NO ACTION ); 
25-11-14 14:31:53.174 | SqlRunner       | main           | INFO : SQL:  CREATE CACHED TABLE multichunk_chunk ( multichunk_id varchar(40) NOT NULL, chunk_checksum varchar(40) NOT NULL, PRIMARY KEY (multichunk_id, chunk_checksum), FOREIGN KEY (multichunk_id) REFERENCES multichunk (id) ON DELETE NO ACTION ON UPDATE NO ACTION, FOREIGN KEY (chunk_checksum) REFERENCES chunk (checksum) ON DELETE NO ACTION ON UPDATE NO ACTION ); 
25-11-14 14:31:53.199 | SqlRunner       | main           | INFO : SQL:  CREATE CACHED TABLE multichunk_muddy ( id varchar(40) NOT NULL, machine_name varchar(255) NOT NULL, machine_version int NOT NULL, PRIMARY KEY (id) ); 
25-11-14 14:31:53.224 | SqlRunner       | main           | INFO : SQL:  CREATE CACHED TABLE known_databases ( id int NOT NULL IDENTITY, database_name varchar(255) NOT NULL, UNIQUE (database_name) ); 
25-11-14 14:31:53.249 | SqlRunner       | main           | INFO : SQL (comment): -- Non-primary indices
25-11-14 14:31:53.250 | SqlRunner       | main           | INFO : SQL:    CREATE INDEX idx_databaseversion_status ON databaseversion (status); 
25-11-14 14:31:53.252 | hsqldb.db.HSQLD | main           | INFO : dataFileCache open start
25-11-14 14:31:53.279 | hsqldb.db.HSQLD | main           | INFO : dataFileCache open end
25-11-14 14:31:53.308 | SqlRunner       | main           | INFO : SQL: CREATE INDEX idx_databaseversion_vectorclock_serialized ON databaseversion (vectorclock_serialized); 
25-11-14 14:31:53.334 | SqlRunner       | main           | INFO : SQL: CREATE INDEX idx_fileversion_path ON fileversion (path); 
25-11-14 14:31:53.359 | SqlRunner       | main           | INFO : SQL: CREATE INDEX idx_fileversion_status ON fileversion (status); 
25-11-14 14:31:53.384 | SqlRunner       | main           | INFO : SQL: CREATE INDEX idx_fileversion_filecontent_checksum ON fileversion (filecontent_checksum); 
25-11-14 14:31:53.409 | SqlRunner       | main           | INFO : SQL (comment): -- Views
25-11-14 14:31:53.410 | SqlRunner       | main           | INFO : SQL:    CREATE VIEW databaseversion_master AS SELECT dbv.*, vc.logicaltime as client_version FROM databaseversion dbv JOIN databaseversion_vectorclock vc on dbv.id=vc.databaseversion_id and dbv.client=vc.client WHERE dbv.status='MASTER'; 
25-11-14 14:31:53.443 | SqlRunner       | main           | INFO : SQL:  CREATE VIEW fileversion_master AS SELECT fv0.* FROM fileversion fv0 JOIN databaseversion dbv ON fv0.databaseversion_id=dbv.id AND dbv.status='MASTER'; 
25-11-14 14:31:53.468 | SqlRunner       | main           | INFO : SQL:  CREATE VIEW fileversion_master_maxversion AS SELECT DISTINCT filehistory_id, MAX(version) version FROM fileversion_master GROUP BY filehistory_id; 
25-11-14 14:31:53.493 | SqlRunner       | main           | INFO : SQL:  CREATE VIEW fileversion_master_last AS SELECT fv.* FROM fileversion_master_maxversion fvmax JOIN fileversion_master fv ON fvmax.filehistory_id=fv.filehistory_id AND fvmax.version=fv.version WHERE fv.status<>'DELETED'; 
25-11-14 14:31:53.526 | SqlRunner       | main           | INFO : SQL (comment): -- Full Views
25-11-14 14:31:53.527 | SqlRunner       | main           | INFO : SQL:    create view filehistory_full as select dbv.status as databaseversion_status, dbv.localtime as databaseversion_localtime, dbv.client as databaseversion_client, dbv.vectorclock_serialized as databaseversion_vectorclock_serialized, fh.* from databaseversion dbv join filehistory fh on dbv.id=fh.databaseversion_id; 
25-11-14 14:31:53.552 | SqlRunner       | main           | INFO : SQL:  create view fileversion_full as select fhf.databaseversion_status, fhf.databaseversion_localtime, fhf.databaseversion_client, fhf.databaseversion_vectorclock_serialized, fv.* from filehistory_full fhf join fileversion fv on fhf.id=fv.filehistory_id and fhf.databaseversion_id=fv.databaseversion_id; 
25-11-14 14:31:53.585 | SqlRunner       | main           | INFO : SQL (comment): -- Functions
25-11-14 14:31:53.586 | SqlRunner       | main           | INFO : SQL (new delimiter): end;
25-11-14 14:31:53.587 | SqlRunner       | main           | INFO : SQL:     create function substr_count(haystack varchar(255), needle varchar(255)) returns integer begin atomic declare strCount integer; declare lastIndex integer;  set strCount = 0; set lastIndex = 1;  while lastIndex <> 0 do set lastIndex = locate(needle, haystack, lastIndex);  if lastIndex <> 0 then set strCount = strCount + 1; set lastIndex = lastIndex + length(needle); end if; end while;  return strCount; end; 
25-11-14 14:31:53.628 | UpOperation     | main           | INFO : 
25-11-14 14:31:53.628 | UpOperation     | main           | INFO : Running 'Sync up' at client QbVWJzIfBRASEXEwGtly ...
25-11-14 14:31:53.628 | UpOperation     | main           | INFO : --------------------------------------------
25-11-14 14:31:53.636 | StatusOperation | main           | INFO : 
25-11-14 14:31:53.637 | StatusOperation | main           | INFO : Running 'Status' at client QbVWJzIfBRASEXEwGtly ...
25-11-14 14:31:53.637 | StatusOperation | main           | INFO : --------------------------------------------
25-11-14 14:31:53.637 | StatusOperation | main           | INFO : Querying current file tree from database ...
25-11-14 14:31:53.638 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event StatusStartSyncExternalEvent (org.syncany.operations.daemon.messages.StatusStartSyncExternalEvent@4087a061) ...
Checking for new or altered files ...25-11-14 14:31:53.644 | StatusOperation | main           | INFO : Analyzing local folder /home/gudron/.storages/selectel_swift_test ...
25-11-14 14:31:53.649 | StatusOperation | main           | FINE : - New file: testfile
25-11-14 14:31:53.649 | StatusOperation | main           | FINE : - New file: testdir
25-11-14 14:31:53.650 | StatusOperation | main           | FINE : - New file: testdir/testfile2
25-11-14 14:31:53.650 | StatusOperation | main           | FINE : - Ignoring file (syncany app-related): .syncany
25-11-14 14:31:53.651 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event StatusEndSyncExternalEvent (org.syncany.operations.daemon.messages.StatusEndSyncExternalEvent@5d463027) ...
25-11-14 14:31:53.652 | AbstractTransfe | main           | INFO : Looking for other running remote operations ...
25-11-14 14:31:53.942 | LsRemoteOperati | main           | INFO : 
25-11-14 14:31:53.943 | LsRemoteOperati | main           | INFO : Running 'Remote Status' at client QbVWJzIfBRASEXEwGtly ...
25-11-14 14:31:53.944 | LsRemoteOperati | main           | INFO : --------------------------------------------
25-11-14 14:31:53.944 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event LsRemoteStartSyncExternalEvent (org.syncany.operations.daemon.messages.LsRemoteStartSyncExternalEvent@55659cad) ...
Checking remote changes ...25-11-14 14:31:53.947 | LsRemoteOperati | main           | INFO : Retrieving remote database list.
25-11-14 14:31:54.087 | LsRemoteOperati | main           | INFO : - No local database versions yet. Assuming all 0 remote database files are unknown. 
25-11-14 14:31:54.090 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event LsRemoteEndSyncExternalEvent (org.syncany.operations.daemon.messages.LsRemoteEndSyncExternalEvent@337b9ff2) ...
25-11-14 14:31:54.091 | UpOperation     | main           | INFO : No remote changes, ready to upload.
25-11-14 14:31:54.092 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpStartSyncExternalEvent (org.syncany.operations.daemon.messages.UpStartSyncExternalEvent@6fb562c3) ...
Starting indexing and upload ...25-11-14 14:31:54.092 | ActionFileHandl | main           | INFO : Starting action for RemoteFile[name=action-up-QbVWJzIfBRASEXEwGtly-1416911512012] ...
25-11-14 14:31:54.093 | ActionFileHandl | main           | INFO : Uploading action file: RemoteFile[name=action-up-QbVWJzIfBRASEXEwGtly-1416911512012]
25-11-14 14:31:54.096 | SwiftTransferMa | main           | INFO : Swift: Uploading /tmp/syncany-action-1882574037160397880.tmp to temp file temp-action-up-QbVWJzIfBRASEXEwGtly-1416911512012
25-11-14 14:31:54.449 | SwiftTransferMa | main           | INFO : Swift: Renaming temp file temp-action-up-QbVWJzIfBRASEXEwGtly-1416911512012 to file /actions/action-up-QbVWJzIfBRASEXEwGtly-1416911512012
25-11-14 14:31:56.291 | ActionFileHandl | main           | INFO : Scheduling action renewal task for every 2 minutes, for RemoteFile[name=action-up-QbVWJzIfBRASEXEwGtly-1416911512012] ...
25-11-14 14:31:56.360 | TransactionAwar | main           | INFO : CLEAN TX: No stale transactions found. No cleansing necessary.
25-11-14 14:31:56.374 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpIndexStartSyncExternalEvent (org.syncany.operations.daemon.messages.UpIndexStartSyncExternalEvent@3f02ae) ...
Indexing 3 new or altered file(s)...25-11-14 14:31:56.375 | Indexer         | main           | FINE : - +File /home/gudron/.storages/selectel_swift_test/testdir
25-11-14 14:31:56.377 | Indexer         | main           | FINE : - /File: testdir (directory/symlink/0-byte-file)
25-11-14 14:31:56.378 | Indexer         | main           | FINE :    * No old file history found, starting new history (path: testdir, FOLDER)
25-11-14 14:31:56.381 | FileVersionComp | main           | INFO :      - [DELETED]: Local file DIFFERS from file version, actual file is NULL, for file testdir
25-11-14 14:31:56.382 | Indexer         | main           | INFO :    * Added file version:    FileVersion [version=1, path=testdir, type=FOLDER, status=NEW, size=4096, lastModified=Tue Nov 25 14:14:23 SAMT 2014, linkTarget=null, checksum=null, updated=Tue Nov 25 14:31:56 SAMT 2014, posixPermissions=rwxrwxr-x, dosAttributes=--a-]
25-11-14 14:31:56.382 | Indexer         | main           | INFO :      based on file version: null
25-11-14 14:31:56.382 | Indexer         | main           | FINE : - +File /home/gudron/.storages/selectel_swift_test/testdir/testfile2
25-11-14 14:31:56.383 | Indexer         | main           | FINE : - +FileContent: /home/gudron/.storages/selectel_swift_test/testdir/testfile2
25-11-14 14:31:56.385 | Indexer         | main           | FINE : - Chunk new: 5dc75f85b86e009ef1d0530fa96e4696828a82ae
25-11-14 14:31:56.387 | CipherSession   | main           | FINE : - Created NEW WRITE secret key HmacSHA256, and added to cache, with salt 4a8e56adf652f877f2a4b927
25-11-14 14:31:56.388 | CipherSession   | main           | FINE : - Created NEW WRITE secret key AES, and added to cache, with salt a77d33d031c9e996b0cfd2ac
25-11-14 14:31:56.390 | CipherSession   | main           | FINE : - Created NEW WRITE secret key Twofish, and added to cache, with salt 819deaf91a4fcf0373fc1eb2
25-11-14 14:31:56.392 | Indexer         | main           | FINE : - +MultiChunk 8df068fcec55706993fbe20596b60a874b922e18
25-11-14 14:31:56.393 | Indexer         | main           | FINE : - Chunk > MultiChunk: 5dc75f85b86e009ef1d0530fa96e4696828a82ae > 8df068fcec55706993fbe20596b60a874b922e18
25-11-14 14:31:56.393 | Indexer         | main           | FINE : - Chunk > FileContent: 5dc75f85b86e009ef1d0530fa96e4696828a82ae > /home/gudron/.storages/selectel_swift_test/testdir/testfile2
25-11-14 14:31:56.394 | Indexer         | main           | FINE : - /File: testdir/testfile2 (checksum 5dc75f85b86e009ef1d0530fa96e4696828a82ae)
25-11-14 14:31:56.394 | Indexer         | main           | FINE :    * No old file history found, starting new history (path: testdir/testfile2, checksum: 5dc75f85b86e009ef1d0530fa96e4696828a82ae)
25-11-14 14:31:56.395 | FileVersionComp | main           | INFO :      - [DELETED]: Local file DIFFERS from file version, actual file is NULL, for file testdir/testfile2
25-11-14 14:31:56.395 | Indexer         | main           | INFO :    * Added file version:    FileVersion [version=1, path=testdir/testfile2, type=FILE, status=NEW, size=32, lastModified=Tue Nov 25 14:14:44 SAMT 2014, linkTarget=null, checksum=5dc75f85b86e009ef1d0530fa96e4696828a82ae, updated=Tue Nov 25 14:31:56 SAMT 2014, posixPermissions=rw-rw-r--, dosAttributes=--a-]
25-11-14 14:31:56.395 | Indexer         | main           | INFO :      based on file version: null
25-11-14 14:31:56.397 | Indexer         | main           | FINE : - +File /home/gudron/.storages/selectel_swift_test/testfile
25-11-14 14:31:56.398 | Indexer         | main           | FINE : - +FileContent: /home/gudron/.storages/selectel_swift_test/testfile
25-11-14 14:31:56.398 | Indexer         | main           | FINE : - Chunk new: 8e2ac4e31e2cfe243b0767ecac700f83ea74a4b1
25-11-14 14:31:56.398 | Indexer         | main           | FINE : - Chunk > MultiChunk: 8e2ac4e31e2cfe243b0767ecac700f83ea74a4b1 > 8df068fcec55706993fbe20596b60a874b922e18
25-11-14 14:31:56.399 | Indexer         | main           | FINE : - Chunk > FileContent: 8e2ac4e31e2cfe243b0767ecac700f83ea74a4b1 > /home/gudron/.storages/selectel_swift_test/testfile
25-11-14 14:31:56.399 | Indexer         | main           | FINE : - /File: testfile (checksum 8e2ac4e31e2cfe243b0767ecac700f83ea74a4b1)
25-11-14 14:31:56.400 | Indexer         | main           | FINE :    * No old file history found, starting new history (path: testfile, checksum: 8e2ac4e31e2cfe243b0767ecac700f83ea74a4b1)
25-11-14 14:31:56.400 | FileVersionComp | main           | INFO :      - [DELETED]: Local file DIFFERS from file version, actual file is NULL, for file testfile
25-11-14 14:31:56.400 | Indexer         | main           | INFO :    * Added file version:    FileVersion [version=1, path=testfile, type=FILE, status=NEW, size=31, lastModified=Tue Nov 25 14:13:46 SAMT 2014, linkTarget=null, checksum=8e2ac4e31e2cfe243b0767ecac700f83ea74a4b1, updated=Tue Nov 25 14:31:56 SAMT 2014, posixPermissions=rw-rw-r--, dosAttributes=--a-]
25-11-14 14:31:56.400 | Indexer         | main           | INFO :      based on file version: null
25-11-14 14:31:56.403 | Indexer         | main           | FINE : - /MultiChunk 8df068fcec55706993fbe20596b60a874b922e18
25-11-14 14:31:56.403 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpIndexEndSyncExternalEvent (org.syncany.operations.daemon.messages.UpIndexEndSyncExternalEvent@3cb7cdc8) ...
25-11-14 14:31:56.404 | Indexer         | main           | FINE : - Looking for deleted files ...
25-11-14 14:31:56.404 | UpOperation     | main           | INFO : Uploading new multichunks ...
25-11-14 14:31:56.406 | UpOperation     | main           | INFO : - Uploading multichunk 8df068fcec55706993fbe20596b60a874b922e18 from /home/gudron/.storages/selectel_swift_test/.syncany/cache/multichunk-8df068fcec55706993fbe20596b60a874b922e18 to RemoteFile[name=multichunk-8df068fcec55706993fbe20596b60a874b922e18] ...
25-11-14 14:31:56.407 | RemoteTransacti | main           | INFO : - Adding file to TX for UPLOAD: /home/gudron/.storages/selectel_swift_test/.syncany/cache/multichunk-8df068fcec55706993fbe20596b60a874b922e18 -> Temp. remote file: RemoteFile[name=temp-bAIDo-multichunk-8df068fcec55706993fbe20596b60a874b922e18], final location: RemoteFile[name=multichunk-8df068fcec55706993fbe20596b60a874b922e18]
25-11-14 14:31:56.409 | UpOperation     | main           | INFO : No DIRTY data found in database (no dirty databases); Nothing to do here.
25-11-14 14:31:56.411 | UpOperation     | main           | INFO : Saving local delta database, version QbVWJzIfBRASEXEwGtly/(QbVWJzIfBRASEXEwGtly1)/T=1416911516404 to file /home/gudron/.storages/selectel_swift_test/.syncany/cache/database-QbVWJzIfBRASEXEwGtly-0000000001 ... 
25-11-14 14:31:56.411 | UpOperation     | main           | INFO : - Saving database to /home/gudron/.storages/selectel_swift_test/.syncany/cache/database-QbVWJzIfBRASEXEwGtly-0000000001 ...
25-11-14 14:31:56.413 | CipherSession   | main           | FINE : - Using CACHED WRITE secret key HmacSHA256, with salt 4a8e56adf652f877f2a4b927
25-11-14 14:31:56.414 | CipherSession   | main           | FINE : - Using CACHED WRITE secret key AES, with salt a77d33d031c9e996b0cfd2ac
25-11-14 14:31:56.414 | CipherSession   | main           | FINE : - Using CACHED WRITE secret key Twofish, with salt 819deaf91a4fcf0373fc1eb2
25-11-14 14:31:56.424 | UpOperation     | main           | INFO : - Uploading local delta database file ...
25-11-14 14:31:56.425 | UpOperation     | main           | INFO : - Uploading /home/gudron/.storages/selectel_swift_test/.syncany/cache/database-QbVWJzIfBRASEXEwGtly-0000000001 to RemoteFile[name=database-QbVWJzIfBRASEXEwGtly-0000000001] ...
25-11-14 14:31:56.425 | RemoteTransacti | main           | INFO : - Adding file to TX for UPLOAD: /home/gudron/.storages/selectel_swift_test/.syncany/cache/database-QbVWJzIfBRASEXEwGtly-0000000001 -> Temp. remote file: RemoteFile[name=temp-cikxb-database-QbVWJzIfBRASEXEwGtly-0000000001], final location: RemoteFile[name=database-QbVWJzIfBRASEXEwGtly-0000000001]
25-11-14 14:31:56.425 | RemoteTransacti | main           | INFO : Starting TX.commit() ...
25-11-14 14:31:56.426 | CipherSession   | main           | FINE : - Using CACHED WRITE secret key HmacSHA256, with salt 4a8e56adf652f877f2a4b927
25-11-14 14:31:56.427 | CipherSession   | main           | FINE : - Using CACHED WRITE secret key AES, with salt a77d33d031c9e996b0cfd2ac
25-11-14 14:31:56.427 | CipherSession   | main           | FINE : - Using CACHED WRITE secret key Twofish, with salt 819deaf91a4fcf0373fc1eb2
25-11-14 14:31:56.442 | RemoteTransacti | main           | INFO : Wrote transaction manifest to temporary file: /home/gudron/.storages/selectel_swift_test/.syncany/cache/temp-transaction-1456859886678660887.tmp
25-11-14 14:31:56.443 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpUploadFileSyncExternalEvent (org.syncany.operations.daemon.messages.UpUploadFileSyncExternalEvent@1cd886cd) ...
Uploading transaction-35d0c395 ...25-11-14 14:31:56.443 | RemoteTransacti | main           | INFO : - Uploading remote transaction file RemoteFile[name=transaction-35d0c395] ...
25-11-14 14:31:56.444 | SwiftTransferMa | main           | INFO : Swift: Uploading /home/gudron/.storages/selectel_swift_test/.syncany/cache/temp-transaction-1456859886678660887.tmp to temp file temp-transaction-35d0c395
25-11-14 14:31:56.706 | SwiftTransferMa | main           | INFO : Swift: Renaming temp file temp-transaction-35d0c395 to file /transactions/transaction-35d0c395
25-11-14 14:31:58.714 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpUploadFileInTransactionSyncExternalEvent (org.syncany.operations.daemon.messages.UpUploadFileInTransactionSyncExternalEvent@712cb19) ...
Uploading 1/2 (376 B, total 0%) ...25-11-14 14:31:58.716 | RemoteTransacti | main           | INFO : - Uploading /home/gudron/.storages/selectel_swift_test/.syncany/cache/multichunk-8df068fcec55706993fbe20596b60a874b922e18 to temp. file RemoteFile[name=temp-bAIDo-multichunk-8df068fcec55706993fbe20596b60a874b922e18] ...
25-11-14 14:31:58.717 | SwiftTransferMa | main           | INFO : Swift: Uploading /home/gudron/.storages/selectel_swift_test/.syncany/cache/multichunk-8df068fcec55706993fbe20596b60a874b922e18 to temp file temp-temp-bAIDo-multichunk-8df068fcec55706993fbe20596b60a874b922e18
25-11-14 14:32:01.108 | SwiftTransferMa | main           | INFO : Swift: Renaming temp file temp-temp-bAIDo-multichunk-8df068fcec55706993fbe20596b60a874b922e18 to file /temporary/temp-bAIDo-multichunk-8df068fcec55706993fbe20596b60a874b922e18
25-11-14 14:32:01.984 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpUploadFileInTransactionSyncExternalEvent (org.syncany.operations.daemon.messages.UpUploadFileInTransactionSyncExternalEvent@e47bced) ...
Uploading 2/2 (808 B, total 32%) ...25-11-14 14:32:01.986 | RemoteTransacti | main           | INFO : - Uploading /home/gudron/.storages/selectel_swift_test/.syncany/cache/database-QbVWJzIfBRASEXEwGtly-0000000001 to temp. file RemoteFile[name=temp-cikxb-database-QbVWJzIfBRASEXEwGtly-0000000001] ...
25-11-14 14:32:01.986 | SwiftTransferMa | main           | INFO : Swift: Uploading /home/gudron/.storages/selectel_swift_test/.syncany/cache/database-QbVWJzIfBRASEXEwGtly-0000000001 to temp file temp-temp-cikxb-database-QbVWJzIfBRASEXEwGtly-0000000001
25-11-14 14:32:03.271 | SwiftTransferMa | main           | INFO : Swift: Renaming temp file temp-temp-cikxb-database-QbVWJzIfBRASEXEwGtly-0000000001 to file /temporary/temp-cikxb-database-QbVWJzIfBRASEXEwGtly-0000000001
25-11-14 14:32:04.903 | RemoteTransacti | main           | INFO : - Moving temp. file RemoteFile[name=temp-bAIDo-multichunk-8df068fcec55706993fbe20596b60a874b922e18] to final location RemoteFile[name=multichunk-8df068fcec55706993fbe20596b60a874b922e18] ...
25-11-14 14:32:05.170 | CommandLineClie | main           | SEVE : Command org.syncany.cli.UpCommand@e92c877 FAILED. 
Command exception, HTTP Status code: 404 => ENTITY_DOES_NOT_EXIST
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.javaswift.joss.exception.HttpStatusToExceptionMapper.getException(HttpStatusToExceptionMapper.java:48)
	at org.javaswift.joss.exception.HttpStatusExceptionUtil.getException(HttpStatusExceptionUtil.java:16)
	at org.javaswift.joss.exception.HttpStatusExceptionUtil.throwException(HttpStatusExceptionUtil.java:10)
	at org.javaswift.joss.command.impl.core.httpstatus.HttpStatusChecker.isOk(HttpStatusChecker.java:30)
	at org.javaswift.joss.command.impl.core.httpstatus.HttpStatusChecker.verifyCode(HttpStatusChecker.java:41)
	at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:50)
	at org.javaswift.joss.command.impl.core.AbstractSecureCommand.call(AbstractSecureCommand.java:31)
	at org.javaswift.joss.client.core.AbstractStoredObject.copyObject(AbstractStoredObject.java:223)
	at org.syncany.plugins.swift.SwiftTransferManager.move(SwiftTransferManager.java:192)
	at org.syncany.plugins.transfer.RetriableTransferManager$5.execute(RetriableTransferManager.java:105)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.move(RetriableTransferManager.java:102)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.move(TransactionAwareTransferManager.java:121)
	at org.syncany.plugins.transfer.RemoteTransaction.moveToFinalLocation(RemoteTransaction.java:207)
	at org.syncany.plugins.transfer.RemoteTransaction.commit(RemoteTransaction.java:125)
	at org.syncany.operations.up.UpOperation.execute(UpOperation.java:148)
	at org.syncany.Client.up(Client.java:114)
	at org.syncany.cli.UpCommand.execute(UpCommand.java:57)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
Error: null
       Refer to help page using '--help'.
```
swift plugin installed via
```
sy plugin install https://www.syncany.org/dist/plugins/snapshots/swift/syncany-plugin-swift-latest-snapshot.jar
```

**Comment by binwiederhier** [comment]
Can you add this to the changelog?
