### ISSUE TITLE
Packaging: Create Mac OSX package task

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#34]
We're looking for someone to build a Mac OSX package for the Syncany command line interface. Ideally it would also be usable for shipping a GUI later on, and could also be created on Linux (so that we can auto-build a new package).

~~The syncany-cli debian package is built by Effing package manager ([FPM](https://github.com/jordansissel/fpm)). For Syncany, I use the [FPM plugin](https://github.com/kenshoo/gradle-fpm-plugin) for Gradle. Also check out the **[detailed description about how Syncany uses FPM](https://github.com/binwiederhier/syncany/blob/master/gradle/fpm/FPM.md)**.~~

~~FPM can (among other things) also build Mac OSX packages, so it'd be really easy to do so. The *.deb package works perfectly, I think, but I haven't even started with the Mac OSX package. In fact, I have no way to test it, because I don't own a Mac.~~

**I am looking for someone to configure and test the Mac OSX package for the Syncany command line client (syncany-cli).**

**Comment by cr0** [comment]
I played around a bit with the said `gradle-macappbundle`. At the end I had to extend the plugin to support Oracle's extended properties. The result is a fork found at [cr0/gradle-macappbundle](https://github.com/cr0/gradle-macappbundle). 
Syncany is now starting, however, no plugins can be loaded and therefore only `local` repositories are working. Installing them using the GUI doesn't work either. The jars are there but they aren't loaded by Syncany. I assume that the classpath does not include the appropriate folder.

**Comment by cr0** [comment]
As far as I can see, it is impossible to extend the classpath using the official Oracle approach. I did some research and found out that Oracle's binary is setting `-Djava.library.path` right before avery other user definable JVM argument is applied:
```
$ ./JavaAppLauncher
-Djava.library.path=/Users/chr/Work/syncany-plugin-gui/build/macApp/Syncany.app/Contents/MacOS
-Djava.library.path=/Users/$APP_USER/.config/syncany/plugins/lib
-Dfile.encoding=utf-8
-Xmx2048M
```
First argument is automatically set and the second java.library.path is set by me.

I propose that `Plugins` is adding the two plugin directories before it loads the plugins and therefore vanishing the need for the `java.library.path` argument.

**Comment by binwiederhier** [comment]
Idea (1): 
You try adding the `~/.config/syncany/plugins/lib/*` to the `Class-Path:` of the `MANIFEST.MF` file of one of the JARs. Not sure if when that's read though.

Idea (2):
You *could* alter the original [appbundler](https://java.net/projects/appbundler). If you speak Objective-C, this might not be so hard. The source file is pretty slim; see [main.m](https://java.net/projects/appbundler/sources/svn/content/appbundler/native/main.m?rev=34). 

You've already altered the macappbundle-gradle plugin right? If so, you could embed the appbundler code in that project ... Not the nicest solution, though.

I'm puzzled by the fact that this is such a hard task. Packaging a Java application for Mac probably happens every day, right?

**Comment by cr0** [comment]
How do I proceed?

I'll use the extended app bundler binary from https://bitbucket.org/infinitekind/appbundler/overview and extend it to support additional class path vars using my googled Objective-C language skills. My forked version of `gradle-macappbundle` will include the binary and replaces the original Oracle one with the one from above. I'll probably drop support for the deprecated Apple Java stuff in `gradle-macappbundle`. So 2 is the way to go. Imho this is the nicest solution since it is also the cleanest.

**Comment by binwiederhier** [comment]
I agree that (2) is the cleanest way to go about this. Let me know if I can help.

**Comment by cr0** [comment]
https://github.com/cr0/gradle-macappbundle/commit/56297b7c140c837dcc4a440693010b6858aa7822 implements the changes and Syncany now starts successfully. :tada:

**Comment by cr0** [comment]
Okay, the pull request sets everything up by placing a zipped .app in the upload folder named `syncany_version`.zip. If you aren't happy with that name change it [here](https://github.com/syncany/syncany-plugin-gui/blob/50eccdc758391e26951532f26757b4c0b170759c/build.gradle#L281).

**Comment by binwiederhier** [comment]
Nice work :+1: 

Looks very good to me from what I see in https://github.com/syncany/syncany-plugin-gui/pull/3. I'll have to make some server side adjustments to process the mac output. I'll do that tonight. 

A few dry-review remarks:
- Do we actually use "net.sf.corn" somewhere?
- Do we cleanup the helper afterwards? Should we maybe store it at the same location and only re-extract it if it isn't there? Wouldn't that make it start faster? *Not a must, just a random thought*

**Comment by cr0** [comment]
I used corn while I was figuring out whats wrong with the classpath, so it became orphaned now.

The helper directory should be removed when Syncany exits. We *could* gain a few seconds if we rely on an already extracted app. But we loose some time again when we verify the helper's version. Don't know what's better.


What's weird: the `createAppZip` doesn't require arch parameters? Is it reusing the last compiled pluginJar?

**Comment by binwiederhier** [comment]
Looks like a big success. I changed quite a few things though. Care to test?

Build:
- https://travis-ci.org/syncany/syncany-plugin-gui/builds/48831831

Result (same files):
- https://www.syncany.org/r/syncany-latest-snapshot-x86_64.app.zip
- https://www.syncany.org/dist/snapshots/syncany-latest-snapshot-x86_64.app.zip
- https://www.syncany.org/dist/snapshots/syncany-0.4.3-alpha+SNAPSHOT.1501292334.git7fd6946-x86_64.app.zip

I only dry reviewed if all the other platform stuff still works; so I need to do that. I doubt that anything will blow up though. :+1:

**Comment by cr0** [comment]
Tested it and it throws a RuntimeException:

```
30-1-15 9:53:00.338 | WebdavTransferM | WR/team2       | SEVE : WebDAV: Unable to list WebDAV directory.
javax.net.ssl.SSLException: java.lang.RuntimeException: pluginListener cannot be null!
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1917)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1874)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1857)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1378)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:823)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:355)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:322)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:313)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:307)
	at org.syncany.plugins.webdav.WebdavTransferManager.list(WebdavTransferManager.java:210)
	at org.syncany.plugins.transfer.RetriableTransferManager$8.execute(RetriableTransferManager.java:138)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.list(RetriableTransferManager.java:135)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.list(TransactionAwareTransferManager.java:139)
	at org.syncany.operations.ls_remote.LsRemoteOperation.listUnknownRemoteDatabases(LsRemoteOperation.java:95)
	at org.syncany.operations.ls_remote.LsRemoteOperation.execute(LsRemoteOperation.java:78)
	at org.syncany.operations.down.DownOperation.listUnknownRemoteDatabases(DownOperation.java:265)
	at org.syncany.operations.down.DownOperation.checkPreconditions(DownOperation.java:240)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:137)
	at org.syncany.operations.watch.WatchOperation.runSync(WatchOperation.java:247)
	at org.syncany.operations.watch.WatchOperation.execute(WatchOperation.java:140)
	at org.syncany.operations.daemon.WatchRunner$1.run(WatchRunner.java:83)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: pluginListener cannot be null!
	at org.syncany.plugins.webdav.WebdavTransferManager$2.isTrusted(WebdavTransferManager.java:459)
	at org.apache.http.conn.ssl.SSLContextBuilder$TrustManagerDelegate.checkServerTrusted(SSLContextBuilder.java:189)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:865)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1351)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:156)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:925)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:860)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
	... 33 more
30-1-15 9:53:00.340 | RetriableTransf | WR/team2       | WARN : Transfer method failed. 1/3 retries. Sleeping 3000ms ...
org.syncany.plugins.transfer.StorageException: javax.net.ssl.SSLException: java.lang.RuntimeException: pluginListener cannot be null!
	at org.syncany.plugins.webdav.WebdavTransferManager.list(WebdavTransferManager.java:239)
	at org.syncany.plugins.transfer.RetriableTransferManager$8.execute(RetriableTransferManager.java:138)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.list(RetriableTransferManager.java:135)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.list(TransactionAwareTransferManager.java:139)
	at org.syncany.operations.ls_remote.LsRemoteOperation.listUnknownRemoteDatabases(LsRemoteOperation.java:95)
	at org.syncany.operations.ls_remote.LsRemoteOperation.execute(LsRemoteOperation.java:78)
	at org.syncany.operations.down.DownOperation.listUnknownRemoteDatabases(DownOperation.java:265)
	at org.syncany.operations.down.DownOperation.checkPreconditions(DownOperation.java:240)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:137)
	at org.syncany.operations.watch.WatchOperation.runSync(WatchOperation.java:247)
	at org.syncany.operations.watch.WatchOperation.execute(WatchOperation.java:140)
	at org.syncany.operations.daemon.WatchRunner$1.run(WatchRunner.java:83)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: pluginListener cannot be null!
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1917)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1874)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1857)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1378)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:823)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:355)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:322)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:313)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:307)
	at org.syncany.plugins.webdav.WebdavTransferManager.list(WebdavTransferManager.java:210)
	... 13 more
Caused by: java.lang.RuntimeException: pluginListener cannot be null!
	at org.syncany.plugins.webdav.WebdavTransferManager$2.isTrusted(WebdavTransferManager.java:459)
	at org.apache.http.conn.ssl.SSLContextBuilder$TrustManagerDelegate.checkServerTrusted(SSLContextBuilder.java:189)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:865)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1351)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:156)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:925)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:860)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
	... 33 more
```

and there are these errors (I don't know if they are related)
```
30-1-15 9:06:42.746 | GuiWebSocketCli | GuiWsClient    | WARN : Web socket connect failure. Waiting, then retrying ...
java.io.IOException: Invalid response code 200
	at org.xnio.http.HttpUpgrade$HttpUpgradeState$UpgradeResultListener.handleEvent(HttpUpgrade.java:378)
	at org.xnio.http.HttpUpgrade$HttpUpgradeState$UpgradeResultListener.handleEvent(HttpUpgrade.java:309)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:539)
```

**Comment by binwiederhier** [comment]
First of: This is entirely unrelated.

I swapped the Syncany SSL certificate two days ago. The certificate we have in our trust store is outdated. The only way to fix this is to do a new `sy connect`. Untested: Try `l=$(sy genlink -s); rm -rf .syncany; sy connect $l`.

**Comment by binwiederhier** [comment]
Oh and: This is only WebDAV relevant right now.

**Comment by binwiederhier** [comment]
Can you check that the helper paths are all correct? I moved around a few things. It was in /gui/helper instead of /org/syncany/gui/helper. Best check the resulting app.zip. I'd do it myself but I'm on the train.

**Comment by binwiederhier** [comment]
Do we have a working Mac version? If so, should we put that on the website?

**Comment by cr0** [comment]
It works fine for me. But we need someone (at best one who never used Syncany before) to confirm if it works for him.

**Comment by binwiederhier** [comment]
Alright. I'll bug one of my coworkers :+1:

**Comment by binwiederhier** [comment]
Fail:
![unnamed](https://cloud.githubusercontent.com/assets/664597/6005807/177275ba-ab05-11e4-80e8-fc319090e20b.png)

@cr0 Can you research this?! I have no idea how to debug this...

**Comment by cr0** [comment]
Oracle Java installed? `/usr/libexec/java_home; java -version`

**Comment by binwiederhier** [comment]
I presume the gradle plugin is now fixed. I already sent him the new link and he'll try again tomorrow. And if he finally decides on a Github username, he might even comment here :+1:

**Comment by binwiederhier** [comment]
@cr0 Same issue with the new binary.

**Comment by cr0** [comment]
Can your coworker please try this debug build? https://www.dropbox.com/s/a6cdq3uobbwtt3g/Syncany-Debug.app.zip?dl=0 At least the error message should tell me a bit more regarding the invalid path.

If the error still exists, please invoke the app using `./Syncany.app/Contents/MacOS/Syncany` via terminal. Since this is a debug build it'll be a bit more chatty than normal. Please post the terminal output here.

**Comment by binwiederhier** [comment]
Same error. No terminal output

**Comment by cr0** [comment]
No terminal output at all and the same error message? Actually it should show the failed java path. 
I've to find another OS X user to cross-validate these findings.

**Comment by binwiederhier** [comment]
I was with him and we did everything you sais step by step. Download the debug app. RemOve the old app. Install the debug app. Run it in the terminal. Same javadirnotfound error pops up. No terminal output.

**Comment by cr0** [comment]
It seems that the binary in the `gradle-macappbundle-plugin` wasn't updated. That's weird. Actually, the javadirnotfound window should show the erroneous folder. I need to get back to `[]` and `()`.. :D

**Comment by cr0** [comment]
New one: https://www.dropbox.com/s/7z7s9pk9i962842/Syncany-Debug2.app.zip?dl=0

**Comment by cr0** [comment]
Received feedback that the current version works. Done. Finally.
