### ISSUE TITLE
GUI (DefaultTrayIcon only): Adding, then removing folder leads to "Index out of bounds" exception.

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#347]
This is a problem in the `DefaultTrayIcon`. To reproduce the following stack trace, click "Add folder ..." (then add a folder), and then remove it again by doing "Remove" in the menu.

```
12-1-15 0:37:11.055 | CommandLineClie | main           | SEVE : Command org.syncany.cli.GuiCommand@636b1b61 FAILED. 
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalArgumentException: Index out of bounds)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.syncany.operations.gui.GuiOperation.startEventDispatchLoop(GuiOperation.java:187)
	at org.syncany.operations.gui.GuiOperation.execute(GuiOperation.java:95)
	at org.syncany.cli.GuiCommand.execute(GuiCommand.java:47)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: java.lang.IllegalArgumentException: Index out of bounds
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.MenuItem.<init>(Unknown Source)
	at org.syncany.gui.tray.DefaultTrayIcon.buildRecentFileChangesMenuItems(DefaultTrayIcon.java:224)
	at org.syncany.gui.tray.DefaultTrayIcon.buildOrUpdateRecentChangesMenuItems(DefaultTrayIcon.java:198)
	at org.syncany.gui.tray.DefaultTrayIcon.buildMenuItems(DefaultTrayIcon.java:155)
	at org.syncany.gui.tray.DefaultTrayIcon.access$100(DefaultTrayIcon.java:58)
	at org.syncany.gui.tray.DefaultTrayIcon$13.run(DefaultTrayIcon.java:397)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	... 10 more
Error: Failed to execute runnable (java.lang.IllegalArgumentException: Index out of bounds)
       Refer to help page using '--help'.
```

**Comment by binwiederhier** [comment]
Can't reproduce anymore. Tried multiple times. Closing for now -- until we meet again.
