### ISSUE TITLE
Daemon debug mode: java.lang.Exception: Invalid syntax

### ISSUE THREAD

**Issue by jaltek** [syncany/syncany#350]
Hi,

I tried to start the syncany daemon with the ```-d``` debug flag which results in
```
$ /home/myfolder/syncany-0.4.2-alpha/bin/sy -d daemon
debug
Application version: 0.4.2-alpha
20-1-15 10:17:40.158 | CommandLineClie | main           | INFO : Application version: 0.4.2-alpha
20-1-15 10:17:40.162 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DaemonCommand@50c87b21 FAILED. 
java.lang.Exception: Invalid syntax, no action given (start, stop, reload, restart, status, force-stop, list, add, remove).
        at org.syncany.cli.DaemonCommand.parseOptions(DaemonCommand.java:68)
        at org.syncany.cli.DaemonCommand.execute(DaemonCommand.java:49)
        at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
        at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
        at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
        at org.syncany.Syncany.main(Syncany.java:55)
Error: Invalid syntax, no action given (start, stop, reload, restart, status, force-stop, list, add, remove).
       Refer to help page using '--help'.
```

Same by passing the desired action:
```
$ /home/myfolder/syncany-0.4.2-alpha/bin/sy -d daemon start
debug
Application version: 0.4.2-alpha
20-1-15 10:21:12.993 | CommandLineClie | main           | INFO : Application version: 0.4.2-alpha
20-1-15 10:21:12.997 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DaemonCommand@50c87b21 FAILED. 
java.lang.Exception: Invalid syntax, unknown action 'start'
        at org.syncany.cli.DaemonCommand.parseDaemonAction(DaemonCommand.java:101)
        at org.syncany.cli.DaemonCommand.parseOptions(DaemonCommand.java:73)
        at org.syncany.cli.DaemonCommand.execute(DaemonCommand.java:49)
        at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
        at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
        at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
        at org.syncany.Syncany.main(Syncany.java:55)
Error: Invalid syntax, unknown action 'start'
       Refer to help page using '--help'.
```

**Comment by binwiederhier** [comment]
Thanks for reporting that. I guess we'll have to hide the options (`-...`) from the shell scripts. To run the daemon in the foreground, run `sy daemon run -d` or `sy -d daemon run`.

**Comment by binwiederhier** [comment]
After thinking about it again, I believe it's not really worth spending too much time on making a smarter bash (and batch, *urgh!*) script for this case. And am hence closing this ticket. Please let me know if anyone objects.
