### ISSUE TITLE
sftp plugin cannot connect syncany link provided

### ISSUE THREAD

**Issue by Kudret** [syncany/syncany#368]
[kudo-deb7-64:/home/bhasdemi/Personal/yengecHD]71 % sy connect syncany://<removed>

Password: 

Creating master key from password (this might take a while) ...
Error: Unable to extract connection settings: java.lang.reflect.InvocationTargetException
       Refer to help page using '--help'.

[kudo-deb7-64:/home/kudret/Personal/yengecHD]72 % sy --debug connect syncany://<removed>
debug
Application version: 0.4.2-alpha
3-2-15 12:30:07.660 | CommandLineClie | main           | INFO : Application version: 0.4.2-alpha
3-2-15 12:30:08.024 | ConnectOperatio | main           | INFO : 
3-2-15 12:30:08.024 | ConnectOperatio | main           | INFO : Running 'Connect'
3-2-15 12:30:08.024 | ConnectOperatio | main           | INFO : --------------------------------------------
3-2-15 12:30:08.025 | ConnectOperatio | main           | INFO : Creating config TO from link: syncany://<removed> ...
3-2-15 12:30:08.028 | ApplicationLink | main           | INFO : - Master salt: <removed>
3-2-15 12:30:08.029 | ApplicationLink | main           | INFO : - Encrypted plugin settings: <removed>
3-2-15 12:30:08.033 | ConnectOperatio | main           | INFO :  - Link is encrypted. Asking for password.

Password: 
3-2-15 12:30:18.186 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event ShowMessageExternalEvent (org.syncany.operations.daemon.messages.ShowMessageExternalEvent@d8d25de) ...

Creating master key from password (this might take a while) ...
3-2-15 12:30:18.191 | CipherUtil      | main           | FINE : - Creating secret key using PBKDF2WithHmacSHA1 with 1,000,000 rounds, key size 512 bit ...

3-2-15 12:30:24.662 | CipherSession   | main           | FINE : - Created NEW READ secret key HmacSHA256, and added to cache, with salt a07d8d45beb10e5285f9f2c8
3-2-15 12:30:25.096 | CipherSession   | main           | FINE : - Created NEW READ secret key AES, and added to cache, with salt 6011426584c8741e65b8d17c
3-2-15 12:30:25.103 | CipherSession   | main           | FINE : - Created NEW READ secret key Twofish, and added to cache, with salt e2acdc3d237feb96f341d435
3-2-15 12:30:25.242 | Plugins         | main           | INFO : - org.syncany.plugins.gui.GuiPlugin
3-2-15 12:30:25.243 | Plugins         | main           | INFO : - org.syncany.plugins.local.LocalTransferPlugin
3-2-15 12:30:25.247 | Plugins         | main           | INFO : - org.syncany.plugins.sftp.SftpTransferPlugin
3-2-15 12:30:25.267 | CommandLineClie | main           | SEVE : Command org.syncany.cli.ConnectCommand@48e9f62 FAILED. 
org.syncany.plugins.transfer.StorageException: Unable to extract connection settings: java.lang.reflect.InvocationTargetException
	at org.syncany.operations.init.ConnectOperation.createConfigTOFromLink(ConnectOperation.java:296)
	at org.syncany.operations.init.ConnectOperation.createConfigTO(ConnectOperation.java:234)
	at org.syncany.operations.init.ConnectOperation.execute(ConnectOperation.java:95)
	at org.syncany.Client.connect(Client.java:175)
	at org.syncany.cli.ConnectCommand.execute(ConnectCommand.java:60)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: org.syncany.plugins.transfer.StorageException: java.lang.reflect.InvocationTargetException
	at org.syncany.operations.init.ApplicationLink.createTransferSettings(ApplicationLink.java:360)
	at org.syncany.operations.init.ApplicationLink.createTransferSettings(ApplicationLink.java:143)
	at org.syncany.operations.init.ConnectOperation.createConfigTOFromLink(ConnectOperation.java:271)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.simpleframework.xml.core.Function.call(Function.java:86)
	at org.simpleframework.xml.core.Caller.validate(Caller.java:158)
	at org.simpleframework.xml.core.Composite.read(Composite.java:203)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
	at org.simpleframework.xml.core.Persister.read(Persister.java:625)
	at org.simpleframework.xml.core.Persister.read(Persister.java:606)
	at org.simpleframework.xml.core.Persister.read(Persister.java:584)
	at org.simpleframework.xml.core.Persister.read(Persister.java:562)
	at org.simpleframework.xml.core.Persister.read(Persister.java:499)
	at org.simpleframework.xml.core.Persister.read(Persister.java:408)
	at org.syncany.operations.init.ApplicationLink.createTransferSettings(ApplicationLink.java:353)
	... 10 more
Caused by: org.syncany.plugins.transfer.StorageException: Not a valid privatekey file at /home/idris/.ssh/id_rsa
	at org.syncany.plugins.sftp.SftpTransferSettings.validate(SftpTransferSettings.java:116)
	... 26 more
Error: Unable to extract connection settings: java.lang.reflect.InvocationTargetException
       Refer to help page using '--help'.

[kudo-deb7-64:/home/kudret/Personal/yengecHD]73 %

**Comment by cr0** [comment]
Your private key is invalid. Can you post it so that we can verify that?.... *Just kidding, never post it :D*

Since we're using jsch, we require the private key to be in OpenSSH key file format.

**Comment by binwiederhier** [comment]
The SFTP plugin with private key auth does not work syncany:// links, I'm afraid. However, this is a perfect opportunity to make that more obvious to the user.

**Comment by cr0** [comment]
It only fails if the path for the private key is different between machines. So it does not fail in _any_ case.

**Comment by binwiederhier** [comment]
In my opinion, Syncany should output something like "Note: syncany://-links don't work with the current configuration. Please connect manually using 'sy connect'".

@cr0 Ideas how to make this configurable for the plugins? Something like `@ApplicationLink(enabled=no)` or `@ApplicationLink(enabled=conditional, not="privatekey")`.

**Comment by cr0** [comment]
Prohibiting it by default is not a good solution because you can also share links between machines you own. And those machines probably are using the same usernames and the private key is therefore stored at the same location.

Furthermore, links containing absolute file locations are likely to fail (not only the private key). So I propose that validate* for `File`s checks if the file exists and if not throw an IOException which we can catch  and fall back to manual connect mode.

* Validate is done in `TransferSettings`, so it's easy to implement the exemplified behaviour.

**Comment by binwiederhier** [comment]
@cr0 That sounds very reasonable and actually better than my suggestion. And finally we have a good way to use the `@Validate` annotation, right :+1:

**Comment by cr0** [comment]
Ok we can deprecate the usage of `java.io.File` at this point since it's superseded by `java.nio.file.Path` (see http://docs.oracle.com/javase/tutorial/essential/io/legacy.html).

So we assume that `Path`s have to exist on the filesystem, if not we throw an error. If someone wants to use relative paths, i.e. paths which are virtual and do not exist in any case, we recommend the usage of `java.net.URI` in favor of simple strings.

(For the moment we can show a deprecated warning when someone uses `File` but we should still support it)

If you'd like, I'm self assigning this.

**Comment by binwiederhier** [comment]
:+1: 

I've often thought about removing `File` in favor of `Path`. But as of today I don't really see the benefit and the hassle would be huge...

**Comment by pimotte** [comment]
While I agree the hassle would be huge, #374 would also benefit from a switch to `Path`. It also provides more information on deletions and such. Hence, I'm not opposed to switching.

**Comment by cr0** [comment]
My intention was to switch from File to Path at plugin API level for now because we should have a stable API before we go beta. And from what I can read we're close to that milestone.

We can still do the change in the core once we get bored ;)
