### ISSUE TITLE
sy down breaks for file created in 1965

### ISSUE THREAD

**Issue by Kudret** [syncany/syncany#374]
kudret@foo:~/yengecHD$ ls -l
total 12
-rwxrwxr-x 1 kudret kudret   91 Feb  5 19:57 check
-rwxrwxr-x 1 kudret kudret  273 Feb  5 19:59 index
drwxrwxr-x 2 kudret kudret 4096 Feb  5 20:02 MD5s
kudret@foo:~/yengecHD$ echo boo > old_file
kudret@foo:~/yengecHD$ touch --date="1965-07-13 19:57" old_file
kudret@foo:~/yengecHD$ sy up --log=/tmp/upload.log
A old_file                           
Sync up finished.
kudret@foo:~/yengecHD$ ls -l
total 16
-rwxrwxr-x 1 kudret kudret   91 Feb  5 19:57 check
-rwxrwxr-x 1 kudret kudret  273 Feb  5 19:59 index
drwxrwxr-x 2 kudret kudret 4096 Feb  5 20:02 MD5s
-rw-rw-r-- 1 kudret kudret    4 Jul 13  1965 old_file
kudret@foo:~/yengecHD$ 

[kudo-deb7-64:/home/kudo/Personal/yengecHD]106 % ls -l
total 12
-rwxrwxr-x 1 kudo users   91 Feb  5 19:57 check
-rwxrwxr-x 1 kudo users  273 Feb  5 19:59 index
drwxrwxr-x 2 kudo users 4096 Feb  5 20:02 MD5s
[kudo-deb7-64:/home/kudo/Personal/yengecHD]107 % sy down --log=/tmp/download.log
Downloading database 1/1 ...Error: Negative time
       Refer to help page using '--help'.

[kudo-deb7-64:/home/kudo/Personal/yengecHD]108 % ls -l
total 12
-rwxrwxr-x 1 kudo users   91 Feb  5 19:57 check
-rwxrwxr-x 1 kudo users  273 Feb  5 19:59 index
drwxrwxr-x 2 kudo users 4096 Feb  5 20:02 MD5s
[kudo-deb7-64:/home/kudo/Personal/yengecHD]109 %

From: /tmp/download.log.o
6-2-15 11:46:43.743 | FileSystemActio | main           | INFO :      - Setting POSIX permissions: rw-rw-r-- ...
6-2-15 11:46:43.744 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DownCommand@13d344e7 FAILED. 
java.lang.IllegalArgumentException: Negative time
	at java.io.File.setLastModified(File.java:1421)
	at org.syncany.operations.down.actions.FileSystemAction.setLastModified(FileSystemAction.java:123)
	at org.syncany.operations.down.actions.FileCreatingFileSystemAction.assembleFileToCache(FileCreatingFileSystemAction.java:85)
	at org.syncany.operations.down.actions.FileCreatingFileSystemAction.createFile(FileCreatingFileSystemAction.java:74)
	at org.syncany.operations.down.actions.FileCreatingFileSystemAction.createFileFolderOrSymlink(FileCreatingFileSystemAction.java:38)
	at org.syncany.operations.down.actions.NewFileSystemAction.execute(NewFileSystemAction.java:42)
	at org.syncany.operations.down.ApplyChangesOperation.applyFileSystemActions(ApplyChangesOperation.java:194)
	at org.syncany.operations.down.ApplyChangesOperation.execute(ApplyChangesOperation.java:103)
	at org.syncany.operations.down.DownOperation.applyWinnersBranch(DownOperation.java:457)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:189)
	at org.syncany.Client.down(Client.java:125)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)

**Comment by marquis-de-muesli** [comment]
See https://bugs.openjdk.java.net/browse/JDK-6791812
Solution: use java.nio to change filetimes

**Comment by Kudret** [comment]
My initial test with 1969-12-31 23:57 did not break sy down due to timezone. This experiment was done in GMT-5 so, 
touch --date="1969-12-31 18:57 " old_file 
can reproduce the problem, as expected.
