### ISSUE TITLE
SFTP plugin's delete() method throws exception when file does not exist; should not

### ISSUE THREAD

**Issue by marquis-de-muesli** [syncany/syncany#383]
Hi there, 
took a queek peek at the my syncany logs today and found something that might be an issue, not sure of it:

```
18-2-15 14:43:06.030 | AbstractTransfe | main           | INFO : Cleaning own old action files ...
18-2-15 14:43:06.498 | AbstractTransfe | main           | INFO : - Deleting own action file RemoteFile[name=action-up-OQifYkVGThBPzieVTPfU-1424222379261] ...
18-2-15 14:43:06.544 | AbstractTransfe | main           | INFO : - Deleting own action file RemoteFile[name=action-up-OQifYkVGThBPzieVTPfU-1424266900803] ...
18-2-15 14:43:09.665 | Cache           | main           | INFO : Cache too large (17574067 KB), deleting until <= 500 MB ...
18-2-15 14:43:09.665 | Cache           | main           | INFO : - Deleting from cache (Tue Feb 17 22:40:17 CET 2015, 4099 KB): multichunk-a1ac04969725c701c188bd779c99b4e9c4668e31
18-2-15 14:43:09.666 | Cache           | main           | INFO : - Deleting from cache (Tue Feb 17 22:40:17 CET 2015, 4099 KB): multichunk-2ae0fdb242bc3c4aff1016c946debe733d335bd100
(..more Deleting from cache)
18-2-15 14:43:23.784 | Cache           | main           | INFO : - Deleting from cache (Tue Feb 17 22:40:42 CET 2015, 3699 KB): multichunk-584a957ca9379e499cf992e8e24e5522af765ed2
18-2-15 14:43:23.785 | Cache           | main           | INFO : - Deleting from cache (Tue Feb 17 22:40:42 CET 2015, 4092 KB): multichunk-ba2b85355d5a61c9f7c22eb18bf8e81f568b3839
18-2-15 14:43:23.794 | UpOperation     | main           | INFO : Sync up done.
18-2-15 14:43:23.850 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpEndSyncExternalEvent (org.syncany.operations.daemon.messages.UpEndSyncExternalEvent@77e3d121) ...
18-2-15 14:43:23.860 | CleanupOperatio | main           | INFO : 
18-2-15 14:43:23.860 | CleanupOperatio | main           | INFO : Running 'Cleanup' at client OQifYkVGThBPzieVTPfU ...
18-2-15 14:43:23.860 | CleanupOperatio | main           | INFO : --------------------------------------------
18-2-15 14:43:23.861 | ApplicationSqlD | main           | INFO : SQL (general_settings): Read cleanupTime  = (not set)
18-2-15 14:43:23.863 | StatusOperation | main           | INFO : 
18-2-15 14:43:23.863 | StatusOperation | main           | INFO : Running 'Status' at client OQifYkVGThBPzieVTPfU ...
18-2-15 14:43:23.863 | StatusOperation | main           | INFO : --------------------------------------------
18-2-15 14:43:23.863 | StatusOperation | main           | INFO : Querying current file tree from database ...
18-2-15 14:43:23.863 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event StatusStartSyncExternalEvent (org.syncany.operations.daemon.messages.StatusStartSyncExternalEvent@3321dbd4) ...
18-2-15 14:43:24.187 | NotificationLis | NotifyThread   | INFO : Waiting for incoming message (10000 ms) ...
18-2-15 14:43:24.674 | StatusOperation | main           | INFO : Analyzing local folder D:\Cloud ...
18-2-15 14:43:32.310 | FileVersionComp | main           | INFO :      - [CHANGED_LAST_MOD_DATE]: Local file DIFFERS from file version, expected MOD. DATE = 
(...more Local file DIFFERS)
18-2-15 14:43:40.803 | ActionFileHandl | ActRenewTim    | INFO : Scheduling action renewal task for every 2 minutes, for RemoteFile[name=action-up-OQifYkVGThBPzieVTPfU-1424266900803] ...
18-2-15 14:43:40.803 | ActionFileHandl | ActRenewTim    | INFO : Uploading action file: RemoteFile[name=action-up-OQifYkVGThBPzieVTPfU-1424267020803]
18-2-15 14:43:40.803 | SftpTransferMan | ActRenewTim    | INFO : SFTP: Uploading C:\(...)\syncany-action-5028117239845095100.tmp to temp file /(...)/temp-action-up-OQifYkVGThBPzieVTPfU-1424267020803
18-2-15 14:43:40.896 | SftpTransferMan | ActRenewTim    | INFO : SFTP: Renaming temp file /(...)/temp-action-up-OQifYkVGThBPzieVTPfU-1424267020803 to file /(...)/action-up-OQifYkVGThBPzieVTPfU-1424267020803
18-2-15 14:43:40.944 | ActionFileHandl | ActRenewTim    | INFO : Deleting action file: RemoteFile[name=action-up-OQifYkVGThBPzieVTPfU-1424266900803]
18-2-15 14:43:40.990 | SftpTransferMan | ActRenewTim    | SEVE : Could not delete file action-up-OQifYkVGThBPzieVTPfU-1424266900803
2: No such file
	at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2833)
	at com.jcraft.jsch.ChannelSftp.rm(ChannelSftp.java:1945)
	at org.syncany.plugins.sftp.SftpTransferManager.delete(SftpTransferManager.java:276)
	at org.syncany.plugins.transfer.RetriableTransferManager$7.execute(RetriableTransferManager.java:127)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.delete(RetriableTransferManager.java:124)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.delete(TransactionAwareTransferManager.java:134)
	at org.syncany.operations.ActionFileHandler.deleteActionFile(ActionFileHandler.java:94)
	at org.syncany.operations.ActionFileHandler.renewActionFile(ActionFileHandler.java:136)
	at org.syncany.operations.ActionFileHandler.access$000(ActionFileHandler.java:48)
	at org.syncany.operations.ActionFileHandler$1.run(ActionFileHandler.java:114)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
18-2-15 14:43:40.990 | RetriableTransf | ActRenewTim    | WARN : Transfer method failed. 1/3 retries. Sleeping 3000ms ...
org.syncany.plugins.transfer.StorageException: 2: No such file
	at org.syncany.plugins.sftp.SftpTransferManager.delete(SftpTransferManager.java:282)
	at org.syncany.plugins.transfer.RetriableTransferManager$7.execute(RetriableTransferManager.java:127)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.delete(RetriableTransferManager.java:124)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.delete(TransactionAwareTransferManager.java:134)
	at org.syncany.operations.ActionFileHandler.deleteActionFile(ActionFileHandler.java:94)
	at org.syncany.operations.ActionFileHandler.renewActionFile(ActionFileHandler.java:136)
	at org.syncany.operations.ActionFileHandler.access$000(ActionFileHandler.java:48)
	at org.syncany.operations.ActionFileHandler$1.run(ActionFileHandler.java:114)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: 2: No such file
	at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2833)
	at com.jcraft.jsch.ChannelSftp.rm(ChannelSftp.java:1945)
	at org.syncany.plugins.sftp.SftpTransferManager.delete(SftpTransferManager.java:276)
```
	
Since then it retries to delete the same file every few seconds, without success.
Just to clarify, the FTP is running fine, and I haven't meddled with any of the syncany files on it.

Thankfully the actual functionality of the program doesn't seem to be affected, i can still add/remove files, although i havent been using it much since.

**Comment by binwiederhier** [comment]
Thanks for reporting this. This is more of a too verbose log message than an actual issue. The static code analysis tool we use always suggests to log all errors -- so we mostly do. Sometimes, errors add more to the confusion. Deleting non-existing files is one of those cases. 

I'll leave this open because we should **remove the log message**.

**Comment by binwiederhier** [comment]
Soo. After looking into this, I am convinced that this was in fact an issue with the SFTP plugin. The contract dictates that if a file does not exist, the `delete()` method should return without error. I [submitted a fix](https://github.com/syncany/syncany-plugin-sftp/commit/155ee2cf00a0dd05083d46c387b4dcbb75a0eb0d) to solve that. It's untested, but I am fairly certain that it'll work. 

@marquis-de-muesli Can you install the new SFTP plugin and see if it works: 

```
sy plugin remove sftp
sy plugin install sftp --snapshot
```

I'll leave this open for now, but I'll consider it fixed and will likely close it in the next few days unless you tell me otherwise :+1:

**Comment by binwiederhier** [comment]
Asumed fixed.
