### ISSUE TITLE
Bad path error connecting to Dropbox repository from Windows

### ISSUE THREAD

**Issue by Lyrrad** [syncany/syncany#398]
Created a Dropbox repository in OS X.

Tried connecting to it in Windows.  Was able to connect to repository, but get error when downloading files.

Appears to be an issue with the path name being passed to Dropbox.
```
syncany down -d

debug
Application version: 0.4.3-alpha
3-3-15 15:39:44.841 | CommandLineClie | main           | INFO : Application version: 0.4.3-alpha
3-3-15 15:39:44.904 | PidFileUtil     | main           | INFO : isProcessRunningWindows(3932) returned java.exe
             3932 Console                    1    105,996 K, process running = true
3-3-15 15:39:44.904 | org.syncany.plu | main           | FINE : Validating required fields
3-3-15 15:39:44.919 | org.syncany.plu | main           | FINE : Validating required fields
3-3-15 15:39:44.919 | DatabaseConnect | main           | INFO : Loading database driver org.hsqldb.jdbcDriver ...
3-3-15 15:39:45.232 | hsqldb.db.HSQLD | main           | INFO : dataFileCache open start
3-3-15 15:39:45.232 | hsqldb.db.HSQLD | main           | INFO : dataFileCache open end
3-3-15 15:39:45.299 | DownOperation   | main           | INFO :
3-3-15 15:39:45.299 | DownOperation   | main           | INFO : Running 'Sync down' at client YOjLwNSPhpTJvzajfgfB ...
3-3-15 15:39:45.299 | DownOperation   | main           | INFO : --------------------------------------------
3-3-15 15:39:45.299 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event DownStartSyncEx
ternalEvent (org.syncany.operations.daemon.messages.DownStartSyncExternalEvent@7048535f) ...
3-3-15 15:39:45.315 | LsRemoteOperati | main           | INFO :
3-3-15 15:39:45.315 | LsRemoteOperati | main           | INFO : Running 'Remote Status' at client YOjLwNSPhpTJvzajfgfB .
..
3-3-15 15:39:45.315 | LsRemoteOperati | main           | INFO : --------------------------------------------
3-3-15 15:39:45.315 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event LsRemoteStartSy
ncExternalEvent (org.syncany.operations.daemon.messages.LsRemoteStartSyncExternalEvent@604b1e1d) ...
Checking remote changes ...3-3-15 15:39:45.331 | LsRemoteOperati | main           | INFO : Retrieving remote database li
st.
3-3-15 15:39:45.331 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DownCommand@7225790e FAILED.
java.lang.IllegalArgumentException: 'path': bad path: must start with "/": "\\synctest\\databases"
        at com.dropbox.core.DbxPath.checkArg(DbxPath.java:48)
        at com.dropbox.core.DbxClient.getMetadataWithChildrenBase(DbxClient.java:174)
        at com.dropbox.core.DbxClient.getMetadataWithChildren(DbxClient.java:148)
        at org.syncany.plugins.dropbox.DropboxTransferManager.list(DropboxTransferManager.java:247)
        at org.syncany.plugins.transfer.RetriableTransferManager$8.execute(RetriableTransferManager.java:138)
        at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
        at org.syncany.plugins.transfer.RetriableTransferManager.list(RetriableTransferManager.java:135)
        at org.syncany.plugins.transfer.TransactionAwareTransferManager.list(TransactionAwareTransferManager.java:139)
        at org.syncany.operations.ls_remote.LsRemoteOperation.listUnknownRemoteDatabases(LsRemoteOperation.java:95)
        at org.syncany.operations.ls_remote.LsRemoteOperation.execute(LsRemoteOperation.java:78)
        at org.syncany.operations.down.DownOperation.listUnknownRemoteDatabases(DownOperation.java:265)
        at org.syncany.operations.down.DownOperation.checkPreconditions(DownOperation.java:240)
        at org.syncany.operations.down.DownOperation.execute(DownOperation.java:137)
        at org.syncany.Client.down(Client.java:125)
        at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
        at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
        at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
        at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
        at org.syncany.Syncany.main(Syncany.java:55)
Error: 'path': bad path: must start with "/": "\\synctest\\databases"
       Refer to help page using '--help'.
```

**Comment by cr0** [comment]
I hope to find some time to fix this tomorrow. This happens because we use new File to concatenate the root path and the path of a file type. We should use URI then there will be no problems with different File.SEPARATORs.

**Comment by cr0** [comment]
Please try [this patch](https://github.com/syncany/syncany-plugin-dropbox/commit/6595e4d59ef107af5520facee344c79955a04ff6). Once you provide positive feedback we'll merge it.

**Comment by Lyrrad** [comment]
I tried it and it works.  I'm able to connect to an existing DropBox repository, download and upload files.

**Comment by binwiederhier** [comment]
@cr0 I'm confused. The network overview shows that [the branch](https://github.com/syncany/syncany-plugin-dropbox/compare/hotfix/issue398) is not merged. Can you double check this?

**Comment by cr0** [comment]
I am confused, too. I did not make the merge because syncany/syncany-plugin-dropbox#3 was blocked by that SonarRunner thing. @MrHug did something to make it work and then... I dont know.

Anyways, the changes are present in the [current dev branch](https://github.com/syncany/syncany-plugin-dropbox/tree/develop/src/main/java/org/syncany/plugins/dropbox).

**Comment by MrHug** [comment]
Pretty sure that is was merged indirectly through: https://github.com/syncany/syncany-plugin-dropbox/pull/5?

**Comment by cr0** [comment]
Yep there's our answer. Thanks!

**Comment by binwiederhier** [comment]
We should probably delete the leftover branch then.

**Comment by cr0** [comment]
![screen shot 2015-04-15 at 17 22 56](https://cloud.githubusercontent.com/assets/854965/7162292/16af0a9a-e394-11e4-9340-86c35ac68f13.png)

Furthermore, the branch is merged according to the branch overview. I'll delete it.

**Comment by binwiederhier** [comment]
:+1:
