### ISSUE TITLE
EC AlgorithmParameters not available error connecting to Dropbox repository

### ISSUE THREAD

**Issue by relan** [syncany/syncany#401]
Successfully created Dropbox repository on OS X 10.10.

Trying to `sy connect` from another machine with Fedora 21:

```
sy connect
Choose a storage plugin. Available plugins are: dropbox, local
Plugin: dropbox

Connection details for dropbox connection:

This plugin needs you to authenticate your account so that Syncany can access it.
Please navigate to the URL below and enter the token:

  https://www.dropbox.com/1/oauth2/authorize?************************

- Token (paste from URL): ******************************************************
- Relative path on Dropbox: /
Error: Unable to connect to repository.
       Refer to help page using '--help'.
```

Log:

```
7-3-15 15:06:52.441 | CommandLineClie | main           | SEVE : Command org.syncany.cli.ConnectCommand@5a61f5df FAILED. 
org.syncany.plugins.transfer.StorageException: Unable to connect to repository.
	at org.syncany.operations.init.ConnectOperation.downloadFile(ConnectOperation.java:357)
	at org.syncany.operations.init.ConnectOperation.execute(ConnectOperation.java:120)
	at org.syncany.Client.connect(Client.java:175)
	at org.syncany.cli.ConnectCommand.execute(ConnectCommand.java:60)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: org.syncany.plugins.transfer.StorageException: com.dropbox.core.DbxException$NetworkIO: javax.net.ssl.SSLException: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: EC AlgorithmParameters not available
	at org.syncany.plugins.dropbox.DropboxTransferManager.download(DropboxTransferManager.java:168)
	at org.syncany.operations.init.ConnectOperation.downloadFile(ConnectOperation.java:353)
	... 7 more
Caused by: com.dropbox.core.DbxException$NetworkIO: javax.net.ssl.SSLException: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: EC AlgorithmParameters not available
	at com.dropbox.core.DbxRequestUtil.startGet(DbxRequestUtil.java:119)
	at com.dropbox.core.DbxClient.startGetSomething(DbxClient.java:403)
	at com.dropbox.core.DbxClient.startGetFile(DbxClient.java:391)
	at com.dropbox.core.DbxClient.getFile(DbxClient.java:345)
	at org.syncany.plugins.dropbox.DropboxTransferManager.download(DropboxTransferManager.java:153)
	... 8 more
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: EC AlgorithmParameters not available
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1894)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1877)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1398)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.dropbox.core.http.StandardHttpRequestor.doGet(StandardHttpRequestor.java:82)
	at com.dropbox.core.DbxRequestUtil.startGet(DbxRequestUtil.java:116)
	... 12 more
Caused by: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: EC AlgorithmParameters not available
	at sun.security.util.ECUtil.getECParameters(ECUtil.java:141)
	at sun.security.util.ECUtil.getECParameterSpec(ECUtil.java:190)
	at sun.security.ssl.JsseJce.getECParameterSpec(JsseJce.java:385)
	at sun.security.ssl.HandshakeMessage$ECDH_ServerKeyExchange.<init>(HandshakeMessage.java:1060)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:277)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:957)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:892)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
	... 18 more
Caused by: java.security.NoSuchAlgorithmException: EC AlgorithmParameters not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:146)
	at sun.security.util.ECUtil.getECParameters(ECUtil.java:139)
	... 27 more
```

Syncany 0.4.3-alpha+SNAPSHOT.1502241739.gite0a28aa
Dropbox plugin 0.4.3-alpha
Fedora 21 x86_64
java-1.8.0-openjdk-1.8.0.31-5.b13.fc21.x86_64

Let me know if you want me to try some patch/branch/etc.

**Comment by MrHug** [comment]
Hmm, I think this might be an issue with OpenJDK rather than the Syncany Dropbox Plugin actually...
http://armoredbarista.blogspot.co.uk/2013/10/how-to-use-ecc-with-openjdk.html

**Comment by cr0** [comment]
It's a bug in openjdk, hence I'm closing this.
See https://bugzilla.redhat.com/show_bug.cgi?id=1167153

**Comment by binwiederhier** [comment]
@relan 
So when does this happen? Every time, or only very rarely? If this happens every time, we should find a workaround, if there is one. If not, we can definitely leave this closed.

**Comment by relan** [comment]
This happens every time I try to `sy connect` to the Dropbox repo.

Looks like this should be fixed on Fedora side though. So I don't insist on looking for a workaround. I think Fedora guys will fix it soon since Syncany is not the only affected software.

**Comment by relan** [comment]
JFYI: I was able to workaround this by adding
```
jdk.tls.disabledAlgorithms=EC, ECDHE, ECDH
```
to `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.31-5.b13.fc21.x86_64/jre/lib/security/java.security`. Now Syncany works as expected.
