### ISSUE TITLE
Mac GUI crashes

### ISSUE THREAD

**Issue by andunix** [syncany/syncany#409]
The Mac GUI crashes when opening the preferences. I'm using OS X 10.10.2. Java is 1.7.0_76 and 1.8.0_31 (default).
When starting the GUI, there is an exception but ist starts.
```
Exception in thread "GuiWsClient" java.lang.NoClassDefFoundError: org/syncany/operations/daemon/messages/api/XmlMessageFactory
	at org.syncany.operations.gui.GuiWebSocketClient.postMessage(GuiWebSocketClient.java:266)
	at org.syncany.operations.gui.GuiWebSocketClient.onRequest(GuiWebSocketClient.java:253)
	at org.syncany.operations.gui.GuiWebSocketClient.sendListWatchesRequest(GuiWebSocketClient.java:156)
	at org.syncany.operations.gui.GuiWebSocketClient.connectAndWait(GuiWebSocketClient.java:142)
	at org.syncany.operations.gui.GuiWebSocketClient$1.run(GuiWebSocketClient.java:101)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.syncany.operations.daemon.messages.api.XmlMessageFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 6 more
```
But if I then select "Preferences" from the menu, it crashes with
```
Error: Failed to execute runnable (java.lang.NoClassDefFoundError: org/syncany/operations/daemon/messages/api/XmlMessageFactory)
       Refer to help page using '--help'.
```

**Comment by andunix** [comment]
With the debug option, I got some more informations. I tried creating the directory `/Users/andreas/Library/Java/Extensions`, but the exception didn't go away.
```
12-3-15 19:55:48.717 | DesktopUtil     | main           | INFO : Autostart (enabled): Adding item to OSX login items
12-3-15 19:55:48.734 | DesktopUtil     | main           | WARN : Autostart: Cannot alter OSX login items.
java.io.IOException: Unable to add autostart for unbundled app (2): /Users/andreas/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr
	at org.syncany.gui.util.DesktopUtil.addLoginItemsEntryOSX(DesktopUtil.java:249)
	at org.syncany.gui.util.DesktopUtil.writeAutostartOSX(DesktopUtil.java:225)
	at org.syncany.gui.util.DesktopUtil.writeAutostart(DesktopUtil.java:133)
	at org.syncany.gui.preferences.GeneralPanel.writeOrDeleteStartupScriptFile(GeneralPanel.java:212)
	at org.syncany.gui.preferences.GeneralPanel.<init>(GeneralPanel.java:77)
	at org.syncany.gui.preferences.PreferencesDialog.buildPanels(PreferencesDialog.java:276)
	at org.syncany.gui.preferences.PreferencesDialog.open(PreferencesDialog.java:91)
	at org.syncany.gui.tray.TrayIcon$3.run(TrayIcon.java:169)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.syncany.operations.gui.GuiOperation.startEventDispatchLoop(GuiOperation.java:206)
	at org.syncany.operations.gui.GuiOperation.execute(GuiOperation.java:99)
	at org.syncany.cli.GuiCommand.execute(GuiCommand.java:48)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
12-3-15 19:55:48.740 | org.apache.http | Finalizer      | FINE : Connection manager is shutting down
12-3-15 19:55:48.741 | org.apache.http | Finalizer      | FINE : http-outgoing-0: Close connection
12-3-15 19:55:48.743 | org.apache.http | Finalizer      | FINE : http-outgoing-0: Close connection
12-3-15 19:55:48.743 | org.apache.http | Finalizer      | FINE : Connection manager shut down
12-3-15 19:55:48.751 | InternalEventBu | main           | INFO : Event bus 'GuiEventBus': Registering PluginsPanel (PluginsPanel {}) ...
12-3-15 19:55:48.783 | InternalEventBu | main           | INFO : Event bus 'GuiEventBus': Posting event PluginManagementRequest (org.syncany.operations.daemon.messages.PluginManagementRequest@5b7e588b) ...
12-3-15 19:55:48.785 | CommandLineClie | main           | SEVE : Command org.syncany.cli.GuiCommand@77efc193 FAILED. 
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NoClassDefFoundError: org/syncany/operations/daemon/messages/api/XmlMessageFactory)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.syncany.operations.gui.GuiOperation.startEventDispatchLoop(GuiOperation.java:206)
	at org.syncany.operations.gui.GuiOperation.execute(GuiOperation.java:99)
	at org.syncany.cli.GuiCommand.execute(GuiCommand.java:48)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: java.lang.NoClassDefFoundError: org/syncany/operations/daemon/messages/api/XmlMessageFactory
	at org.syncany.operations.gui.GuiWebSocketClient.postMessage(GuiWebSocketClient.java:266)
	at org.syncany.operations.gui.GuiWebSocketClient.onRequest(GuiWebSocketClient.java:253)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at org.syncany.config.InternalEventBus.post(InternalEventBus.java:76)
	at org.syncany.gui.preferences.PluginsPanel.refreshPluginList(PluginsPanel.java:557)
	at org.syncany.gui.preferences.PluginsPanel.createControls(PluginsPanel.java:115)
	at org.syncany.gui.preferences.PluginsPanel.<init>(PluginsPanel.java:103)
	at org.syncany.gui.preferences.PreferencesDialog.buildPanels(PreferencesDialog.java:277)
	at org.syncany.gui.preferences.PreferencesDialog.open(PreferencesDialog.java:91)
	at org.syncany.gui.tray.TrayIcon$3.run(TrayIcon.java:169)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	... 10 more
Error: Failed to execute runnable (java.lang.NoClassDefFoundError: org/syncany/operations/daemon/messages/api/XmlMessageFactory)
       Refer to help page using '--help'.

12-3-15 19:55:48.786 | GuiOperation    | Thread-1       | INFO : Releasing SWT Resources
12-3-15 19:55:48.786 | OSXTrayIcon     | Thread-5       | INFO : Cleaning up notification helper...
```

**Comment by cr0** [comment]
The first error (or more precisely warning) message (`Cannot alter OSX login items.`) is unrelated.

Am I correct that you ran the gui using `sy gui`? This seems like you're using the current gui version with an old version of Syncany. What's your Syncany version (`sy -v`)? Could you update the Syncany core? 

*Hm I notice that we haven't updated the homebrew recipe for a while*

**Comment by andunix** [comment]
I installes syncany with Homebrew and then the gui plugin with syncany itself.
```
$ sy plugin install gui
Plugin successfully installed from https://www.syncany.org/dist/plugins/releases/gui/syncany-plugin-gui-macosx-x86_64-0.4.3-alpha.jar
Install location: /Users/andreas/.config/syncany/plugins/lib/syncany-plugin-gui-0.4.3-alpha.jar
```
```
$ sy -v
0.4.2-alpha+SNAPSHOT.1503111913.gitUNKNOWN
```
How can I update syncany to 0.4.3?

**Comment by cr0** [comment]
I'll give you a ping once I've updated the home brew formula (which will happen within an hour). Then you can update sy using home brew. It should also solve that error.

**Comment by andunix** [comment]
I just had a look and I found that changing lines 5-7 worked:
```
  url "https://codeload.github.com/syncany/syncany/tar.gz/v0.4.3-alpha"
  sha256 "1e749bf505c0e2dcecfbb08b929711dc179b70b44d5f93e8e2558f628abcb735"
  version "0.4.3-alpha"
```

**Comment by andunix** [comment]
Updating syncany to 0.4.3 resolved the issue for me. Thanks alot!

**Comment by cr0** [comment]
Yep that's all you need to do. Feel free to create a pr.
