### ISSUE TITLE
sftp plugin issues with non standard port?

### ISSUE THREAD

**Issue by spidernik84** [syncany/syncany#423]
Hello,

I'm using syncany to sync a local directory via sftp to my remote VPS. The connection is public key based and to a non-standard port. The sync fails. 
I suspect a problem with how the plugin parses the port, since the four digit number of the port is translated to a x,xxx with a comma. Is this a visual glitch in the debug or is syncany mangling the port? 

I'd like to point out that this was working fine before I changed the port from 22. A plain, key based ssh connection to the new port works fine.

Syncany version: 0.4.2-alpha+SNAPSHOT.1501231844.gitUNKNOWN
SFTP plugin version: 0.4.3-alpha

Thanks! 
```
sy down --debug
debug
Application version: 0.4.2-alpha+SNAPSHOT.1501231844.gitUNKNOWN
29-3-15 13:55:52.212 | CommandLineClie | main           | INFO : Application version: 0.4.2-alpha+SNAPSHOT.1501231844.gitUNKNOWN
29-3-15 13:55:52.222 | org.syncany.plu | main           | FINE : Validating required fields
29-3-15 13:55:52.235 | org.syncany.plu | main           | FINE : Validating required fields
29-3-15 13:55:52.240 | DatabaseConnect | main           | INFO : Loading database driver org.hsqldb.jdbcDriver ...
29-3-15 13:55:52.590 | hsqldb.db.HSQLD | main           | INFO : dataFileCache open start
29-3-15 13:55:52.596 | hsqldb.db.HSQLD | main           | INFO : dataFileCache open end
29-3-15 13:55:52.664 | DownOperation   | main           | INFO :
29-3-15 13:55:52.664 | DownOperation   | main           | INFO : Running 'Sync down' at client HIrNFrFxlwytiPWtLrzv ...
29-3-15 13:55:52.665 | DownOperation   | main           | INFO : --------------------------------------------
29-3-15 13:55:52.666 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event DownStartSyncExternalEvent (org.syncany.operations.daemon.messages.DownStartSyncExternalEvent@314c8b4a) ...
29-3-15 13:55:52.669 | LsRemoteOperati | main           | INFO :
29-3-15 13:55:52.669 | LsRemoteOperati | main           | INFO : Running 'Remote Status' at client HIrNFrFxlwytiPWtLrzv ...
29-3-15 13:55:52.669 | LsRemoteOperati | main           | INFO : --------------------------------------------
29-3-15 13:55:52.670 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event LsRemoteStartSyncExternalEvent (org.syncany.operations.daemon.messages.LsRemoteStartSyncExternalEvent@5246a3b3) ...
Checking remote changes ...29-3-15 13:55:52.673 | LsRemoteOperati | main           | INFO : Retrieving remote database list.
29-3-15 13:55:52.681 | SftpTransferMan | main           | INFO : SFTP client connecting to mail.myhost.io:7,933 ...
29-3-15 13:55:52.683 | SftpTransferMan | main           | INFO : SFTP: Using pubkey authentication with key /Users/myusername/.ssh/id_rsa
29-3-15 13:55:53.029 | SftpTransferMan | main           | WARN : SFTP client connection failed.
java.lang.NullPointerException
	at com.jcraft.jsch.Session.checkHost(Session.java:802)
	at com.jcraft.jsch.Session.connect(Session.java:342)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
	at org.syncany.plugins.sftp.SftpTransferManager.list(SftpTransferManager.java:304)
	at org.syncany.plugins.transfer.RetriableTransferManager$8.execute(RetriableTransferManager.java:138)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.list(RetriableTransferManager.java:135)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.list(TransactionAwareTransferManager.java:139)
	at org.syncany.operations.ls_remote.LsRemoteOperation.listUnknownRemoteDatabases(LsRemoteOperation.java:95)
	at org.syncany.operations.ls_remote.LsRemoteOperation.execute(LsRemoteOperation.java:78)
	at org.syncany.operations.down.DownOperation.listUnknownRemoteDatabases(DownOperation.java:265)
	at org.syncany.operations.down.DownOperation.checkPreconditions(DownOperation.java:240)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:137)
	at org.syncany.Client.down(Client.java:125)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
29-3-15 13:55:53.031 | RetriableTransf | main           | WARN : Transfer method failed. 1/3 retries. Sleeping 3000ms ...
org.syncany.plugins.transfer.StorageException: java.lang.NullPointerException
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:162)
	at org.syncany.plugins.sftp.SftpTransferManager.list(SftpTransferManager.java:304)
	at org.syncany.plugins.transfer.RetriableTransferManager$8.execute(RetriableTransferManager.java:138)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.list(RetriableTransferManager.java:135)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.list(TransactionAwareTransferManager.java:139)
	at org.syncany.operations.ls_remote.LsRemoteOperation.listUnknownRemoteDatabases(LsRemoteOperation.java:95)
	at org.syncany.operations.ls_remote.LsRemoteOperation.execute(LsRemoteOperation.java:78)
	at org.syncany.operations.down.DownOperation.listUnknownRemoteDatabases(DownOperation.java:265)
	at org.syncany.operations.down.DownOperation.checkPreconditions(DownOperation.java:240)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:137)
	at org.syncany.Client.down(Client.java:125)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: java.lang.NullPointerException
	at com.jcraft.jsch.Session.checkHost(Session.java:802)
	at com.jcraft.jsch.Session.connect(Session.java:342)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
	... 16 more
29-3-15 13:55:56.033 | RetriableTransf | main           | WARN : Retrying method: 1/3 ...
29-3-15 13:55:56.034 | SftpTransferMan | main           | INFO : SFTP client connecting to mail.myhost.io:7,933 ...
29-3-15 13:55:56.035 | SftpTransferMan | main           | INFO : SFTP: Using pubkey authentication with key /Users/myusername/.ssh/id_rsa
29-3-15 13:55:56.227 | SftpTransferMan | main           | WARN : SFTP client connection failed.
java.lang.NullPointerException
	at com.jcraft.jsch.Session.checkHost(Session.java:802)
	at com.jcraft.jsch.Session.connect(Session.java:342)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
	at org.syncany.plugins.sftp.SftpTransferManager.list(SftpTransferManager.java:304)
	at org.syncany.plugins.transfer.RetriableTransferManager$8.execute(RetriableTransferManager.java:138)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.list(RetriableTransferManager.java:135)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.list(TransactionAwareTransferManager.java:139)
	at org.syncany.operations.ls_remote.LsRemoteOperation.listUnknownRemoteDatabases(LsRemoteOperation.java:95)
	at org.syncany.operations.ls_remote.LsRemoteOperation.execute(LsRemoteOperation.java:78)
	at org.syncany.operations.down.DownOperation.listUnknownRemoteDatabases(DownOperation.java:265)
	at org.syncany.operations.down.DownOperation.checkPreconditions(DownOperation.java:240)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:137)
	at org.syncany.Client.down(Client.java:125)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
29-3-15 13:55:56.228 | RetriableTransf | main           | WARN : Transfer method failed. 2/3 retries. Sleeping 3000ms ...
org.syncany.plugins.transfer.StorageException: java.lang.NullPointerException
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:162)
	at org.syncany.plugins.sftp.SftpTransferManager.list(SftpTransferManager.java:304)
	at org.syncany.plugins.transfer.RetriableTransferManager$8.execute(RetriableTransferManager.java:138)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.list(RetriableTransferManager.java:135)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.list(TransactionAwareTransferManager.java:139)
	at org.syncany.operations.ls_remote.LsRemoteOperation.listUnknownRemoteDatabases(LsRemoteOperation.java:95)
	at org.syncany.operations.ls_remote.LsRemoteOperation.execute(LsRemoteOperation.java:78)
	at org.syncany.operations.down.DownOperation.listUnknownRemoteDatabases(DownOperation.java:265)
	at org.syncany.operations.down.DownOperation.checkPreconditions(DownOperation.java:240)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:137)
	at org.syncany.Client.down(Client.java:125)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: java.lang.NullPointerException
	at com.jcraft.jsch.Session.checkHost(Session.java:802)
	at com.jcraft.jsch.Session.connect(Session.java:342)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
	... 16 more
29-3-15 13:55:59.232 | RetriableTransf | main           | WARN : Retrying method: 2/3 ...
29-3-15 13:55:59.232 | SftpTransferMan | main           | INFO : SFTP client connecting to mail.myhost.io:7,933 ...
29-3-15 13:55:59.233 | SftpTransferMan | main           | INFO : SFTP: Using pubkey authentication with key /Users/myusername/.ssh/id_rsa
29-3-15 13:55:59.468 | SftpTransferMan | main           | WARN : SFTP client connection failed.
java.lang.NullPointerException
	at com.jcraft.jsch.Session.checkHost(Session.java:802)
	at com.jcraft.jsch.Session.connect(Session.java:342)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
	at org.syncany.plugins.sftp.SftpTransferManager.list(SftpTransferManager.java:304)
	at org.syncany.plugins.transfer.RetriableTransferManager$8.execute(RetriableTransferManager.java:138)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.list(RetriableTransferManager.java:135)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.list(TransactionAwareTransferManager.java:139)
	at org.syncany.operations.ls_remote.LsRemoteOperation.listUnknownRemoteDatabases(LsRemoteOperation.java:95)
	at org.syncany.operations.ls_remote.LsRemoteOperation.execute(LsRemoteOperation.java:78)
	at org.syncany.operations.down.DownOperation.listUnknownRemoteDatabases(DownOperation.java:265)
	at org.syncany.operations.down.DownOperation.checkPreconditions(DownOperation.java:240)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:137)
	at org.syncany.Client.down(Client.java:125)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
29-3-15 13:55:59.469 | RetriableTransf | main           | WARN : Transfer method failed. No retries left. Throwing exception.
org.syncany.plugins.transfer.StorageException: java.lang.NullPointerException
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:162)
	at org.syncany.plugins.sftp.SftpTransferManager.list(SftpTransferManager.java:304)
	at org.syncany.plugins.transfer.RetriableTransferManager$8.execute(RetriableTransferManager.java:138)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.list(RetriableTransferManager.java:135)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.list(TransactionAwareTransferManager.java:139)
	at org.syncany.operations.ls_remote.LsRemoteOperation.listUnknownRemoteDatabases(LsRemoteOperation.java:95)
	at org.syncany.operations.ls_remote.LsRemoteOperation.execute(LsRemoteOperation.java:78)
	at org.syncany.operations.down.DownOperation.listUnknownRemoteDatabases(DownOperation.java:265)
	at org.syncany.operations.down.DownOperation.checkPreconditions(DownOperation.java:240)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:137)
	at org.syncany.Client.down(Client.java:125)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: java.lang.NullPointerException
	at com.jcraft.jsch.Session.checkHost(Session.java:802)
	at com.jcraft.jsch.Session.connect(Session.java:342)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
	... 16 more
29-3-15 13:55:59.470 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DownCommand@12843fce FAILED.
org.syncany.plugins.transfer.StorageException: java.lang.NullPointerException
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:162)
	at org.syncany.plugins.sftp.SftpTransferManager.list(SftpTransferManager.java:304)
	at org.syncany.plugins.transfer.RetriableTransferManager$8.execute(RetriableTransferManager.java:138)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.list(RetriableTransferManager.java:135)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.list(TransactionAwareTransferManager.java:139)
	at org.syncany.operations.ls_remote.LsRemoteOperation.listUnknownRemoteDatabases(LsRemoteOperation.java:95)
	at org.syncany.operations.ls_remote.LsRemoteOperation.execute(LsRemoteOperation.java:78)
	at org.syncany.operations.down.DownOperation.listUnknownRemoteDatabases(DownOperation.java:265)
	at org.syncany.operations.down.DownOperation.checkPreconditions(DownOperation.java:240)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:137)
	at org.syncany.Client.down(Client.java:125)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: java.lang.NullPointerException
	at com.jcraft.jsch.Session.checkHost(Session.java:802)
	at com.jcraft.jsch.Session.connect(Session.java:342)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
	... 16 more
Error: java.lang.NullPointerException
       Refer to help page using '--help'.
```

**Comment by pimotte** [comment]
I'm pretty sure the comma in the log is purely a logging issue (in other contexts having human readable numbers makes more sense).

Both your syncany and plugin versions are pretty outdated. Can you try updating to the latest versions and see if this issue persists?

**Comment by spidernik84** [comment]
Thanks for the quick reply!

As for syncany itself I now removed it and reinstalled by appending --HEAD to brew (I'm on OS X), so the version is now the following: 0.4.5-alpha+SNAPSHOT.1503291236.git1f31213

The plugin version seems to be the latest, though!

```
sy plugin list
Id      | Name            | Local Version                              | Type   | Remote Version | Updatable | Provided By
--------+-----------------+--------------------------------------------+--------+----------------+-----------+-------------
dropbox | Dropbox         |                                            |        | 0.4.4-alpha    |           | Syncany Team
flickr  | Flickr          |                                            |        | 0.4.1-alpha    |           | Syncany Team
ftp     | FTP             |                                            |        | 0.4.0-alpha    |           | Syncany Team
gui     | GUI             |                                            |        | 0.4.4-alpha    |           | Syncany Team
local   | Local           | 0.4.5-alpha+SNAPSHOT.1503291236.git1f31213 | Global |                |           | Syncany Team
raid0   | RAID0           |                                            |        | 0.4.0-alpha    |           | Syncany Team
s3      | Amazon S3       |                                            |        | 0.4.0-alpha    |           | Syncany Team
samba   | Samba           |                                            |        | 0.4.1-alpha    |           | Syncany Team
sftp    | SFTP            | 0.4.3-alpha                                | User   | 0.4.3-alpha    |           | Syncany Team
swift   | OpenStack Swift |                                            |        | 0.4.0-alpha    |           | Syncany Team
webdav  | WebDAV          |                                            |        | 0.4.0-alpha    |           | Syncany Team
```

The error persists:

```
sy down --debug
debug
Application version: 0.4.5-alpha+SNAPSHOT.1503291236.git1f31213
29-3-15 14:40:13.537 | CommandLineClie | main           | INFO : Application version: 0.4.5-alpha+SNAPSHOT.1503291236.git1f31213
29-3-15 14:40:13.547 | org.syncany.plu | main           | FINE : Validating required fields
29-3-15 14:40:13.562 | org.syncany.plu | main           | FINE : Validating required fields
29-3-15 14:40:13.568 | DatabaseConnect | main           | INFO : Loading database driver org.hsqldb.jdbcDriver ...
29-3-15 14:40:13.938 | hsqldb.db.HSQLD | main           | INFO : dataFileCache open start
29-3-15 14:40:13.945 | hsqldb.db.HSQLD | main           | INFO : dataFileCache open end
29-3-15 14:40:14.008 | DownOperation   | main           | INFO :
29-3-15 14:40:14.009 | DownOperation   | main           | INFO : Running 'Sync down' at client HIrNFrFxlwytiPWtLrzv ...
29-3-15 14:40:14.009 | DownOperation   | main           | INFO : --------------------------------------------
29-3-15 14:40:14.010 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event DownStartSyncExternalEvent (org.syncany.operations.daemon.messages.DownStartSyncExternalEvent@68c87fc3) ...
29-3-15 14:40:14.013 | LsRemoteOperati | main           | INFO :
29-3-15 14:40:14.013 | LsRemoteOperati | main           | INFO : Running 'Remote Status' at client HIrNFrFxlwytiPWtLrzv ...
29-3-15 14:40:14.014 | LsRemoteOperati | main           | INFO : --------------------------------------------
29-3-15 14:40:14.014 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event LsRemoteStartSyncExternalEvent (org.syncany.operations.daemon.messages.LsRemoteStartSyncExternalEvent@24361cfc) ...
Checking remote changes ...29-3-15 14:40:14.018 | LsRemoteOperati | main           | INFO : Retrieving remote database list.
29-3-15 14:40:14.031 | SftpTransferMan | main           | INFO : SFTP client connecting to mail.myhost.io:7,933 ...
29-3-15 14:40:14.032 | SftpTransferMan | main           | INFO : SFTP: Using pubkey authentication with key /Users/myusername/.ssh/id_rsa
29-3-15 14:40:14.503 | SftpTransferMan | main           | WARN : SFTP client connection failed.
java.lang.NullPointerException
	at com.jcraft.jsch.Session.checkHost(Session.java:802)
	at com.jcraft.jsch.Session.connect(Session.java:342)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
	at org.syncany.plugins.sftp.SftpTransferManager.list(SftpTransferManager.java:309)
	at org.syncany.plugins.transfer.RetriableTransferManager$8.execute(RetriableTransferManager.java:138)
	at org.syncany.plugins.transfer.RetriableTransferManager.retryMethod(RetriableTransferManager.java:197)
	at org.syncany.plugins.transfer.RetriableTransferManager.list(RetriableTransferManager.java:135)
	at org.syncany.plugins.transfer.TransactionAwareTransferManager.list(TransactionAwareTransferManager.java:139)
	at org.syncany.operations.ls_remote.LsRemoteOperation.listUnknownRemoteDatabases(LsRemoteOperation.java:95)
	at org.syncany.operations.ls_remote.LsRemoteOperation.execute(LsRemoteOperation.java:78)
	at org.syncany.operations.down.DownOperation.listUnknownRemoteDatabases(DownOperation.java:265)
	at org.syncany.operations.down.DownOperation.checkPreconditions(DownOperation.java:240)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:137)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
	at org.syncany.Syncany.main(Syncany.java:55)
29-3-15 14:40:14.504 | RetriableTransf | main           | WARN : Transfer method failed. 1/3 retries. Sleeping 3000ms ...

```

I'd be happy to provide more details, I suppose this debug is far from being helpful.
Thanks again.

**Comment by pimotte** [comment]
Can you update to the plugin snapshot (remove the plugin, then `sy plugin install sftp --snapshot`) and try again?

**Comment by binwiederhier** [comment]
Make sure to remove the old plugin first `sy plugin remove sftp`, then `sy plugin install sftp --snapshot`. The `sy update` command had trouble with the `--snapshot` flag lately (fixed in 0.4.5)

**Comment by spidernik84** [comment]
Thanks guys, the problem does not occur in the latest version of the plugin. I can now sync three different clients to the same VPS. Apologies for not trying right away with the new version, I thought the one listed in the sy plugin list was reasonably up to date.
Thanks for responding so quickly, Syncany is great.

**Comment by cr0** [comment]
Don't worry!  I hereby consider this solved.

@binwiederhier Only the windows version of the command was buggy.

**Comment by binwiederhier** [comment]
@cr0 Right. I remember ...
Should we release a new sftp plugin version then? If the current snapshot works?

**Comment by pimotte** [comment]
LTLATI (That's short for: "Learn To Look At The IRC")
