### ISSUE TITLE
sy daemon stop reports differently in logs and stderr

### ISSUE THREAD

**Issue by Kudret** [syncany/syncany#424]
$ sy daemon stop
Stopping daemon: .......... Failed to stop process 2427. Try 'force-stop'. EXITING.

$ tail -F ~/.config/syncany/logs/synacny.log.0
29-3-15 19:54:23.136 | NotificationLis | NotifyThread   | INFO : Waiting for incoming message (10000 ms) ...
29-3-15 19:54:23.685 | NotificationLis | NotifyThread   | INFO : Waiting for incoming message (10000 ms) ...
29-3-15 19:54:32.740 | NotificationLis | NotifyThread   | INFO : Waiting for incoming message (10000 ms) ...
29-3-15 19:54:33.147 | NotificationLis | NotifyThread   | INFO : Waiting for incoming message (10000 ms) ...
29-3-15 19:54:33.691 | NotificationLis | NotifyThread   | INFO : Waiting for incoming message (10000 ms) ...
29-3-15 19:54:41.681 | ControlServer   | Thread-4       | INFO : Control file: Received shutdown command. Shutting down.
29-3-15 19:54:41.681 | InternalEventBu | Thread-4       | INFO : Event bus 'LocalEventBus': Posting event ControlCommand (SHUTDOWN) ...
29-3-15 19:54:41.682 | DaemonOperation | Thread-4       | INFO : SHUTDOWN requested.
29-3-15 19:54:41.682 | DaemonOperation | Thread-4       | INFO : Stopping web server ...
29-3-15 19:54:41.682 | WebServer       | Thread-4       | INFO : Shutting down websocket server.
29-3-15 19:54:41.683 | DaemonOperation | Thread-4       | INFO : Stopping watch server ...
29-3-15 19:54:41.683 | WatchServer     | Thread-4       | INFO : Stopping watch server ...  
29-3-15 19:54:41.683 | WatchServer     | Thread-4       | INFO : - Stopping watch operation at /home/kudret/ntck ...
29-3-15 19:54:41.683 | WatchOperation  | Thread-4       | INFO : Stop requested, but sync is NOT running. Immediately stopping thread.
29-3-15 19:54:41.683 | WatchOperation  | Thread-4       | INFO : STOPPING WATCH /home/kudret/ntck ...
29-3-15 19:54:41.683 | WatchOperation  | WR/ntck        | INFO : Sync loop INTERRUPTED. STOPPING.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.syncany.operations.watch.WatchOperation.execute(WatchOperation.java:144)
	at org.syncany.operations.daemon.WatchRunner$1.run(WatchRunner.java:83)
	at java.lang.Thread.run(Thread.java:745)
29-3-15 19:54:41.716 | WatchOperation  | WR/ntck        | INFO : Stopping notification listener for /home/kudret/ntck ...
29-3-15 19:54:41.683 | WatchServer     | Thread-4       | INFO : - Stopping watch operation at /home/kudret/piHD ...
29-3-15 19:54:41.716 | NotificationLis | WR/ntck        | INFO : Stopping notification listener thread ...
29-3-15 19:54:41.716 | WatchOperation  | Thread-4       | INFO : Stop requested, but sync is NOT running. Immediately stopping thread.
29-3-15 19:54:41.716 | WatchOperation  | Thread-4       | INFO : STOPPING WATCH /home/kudret/piHD ...
29-3-15 19:54:41.716 | WatchOperation  | WR/ntck        | INFO : Stopping recursive watcher for /home/kudret/ntck ...
29-3-15 19:54:41.716 | WatchOperation  | WR/piHD        | INFO : Sync loop INTERRUPTED. STOPPING.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.syncany.operations.watch.WatchOperation.execute(WatchOperation.java:144)
	at org.syncany.operations.daemon.WatchRunner$1.run(WatchRunner.java:83)
	at java.lang.Thread.run(Thread.java:745)
29-3-15 19:54:41.716 | NotificationLis | NotifyThread   | INFO : Notification connection down: Socket closed, sleeping 5000ms, then trying a re-connect ...
29-3-15 19:54:41.716 | WatchServer     | Thread-4       | INFO : - Stopping watch operation at /home/kudret/yengecHD ...
29-3-15 19:54:41.717 | NotificationLis | NotifyThread   | INFO : Notification listener interrupted.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.syncany.operations.watch.NotificationListener$SocketThread.run(NotificationListener.java:255)
29-3-15 19:54:41.722 | NotificationLis | NotifyThread   | INFO : STOPPED notification listener!
29-3-15 19:54:41.716 | WatchOperation  | WR/piHD        | INFO : Stopping notification listener for /home/kudret/piHD ...
29-3-15 19:54:41.723 | NotificationLis | WR/piHD        | INFO : Stopping notification listener thread ...
29-3-15 19:54:41.717 | WatchOperation  | Thread-4       | INFO : Stop requested, but sync is NOT running. Immediately stopping thread.
29-3-15 19:54:41.723 | WatchOperation  | Thread-4       | INFO : STOPPING WATCH /home/kudret/yengecHD ...
29-3-15 19:54:41.723 | WatchOperation  | WR/piHD        | INFO : Stopping recursive watcher for /home/kudret/piHD ...
29-3-15 19:54:41.723 | WatchOperation  | WR/yengecHD    | INFO : Sync loop INTERRUPTED. STOPPING.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.syncany.operations.watch.WatchOperation.execute(WatchOperation.java:144)
	at org.syncany.operations.daemon.WatchRunner$1.run(WatchRunner.java:83)
	at java.lang.Thread.run(Thread.java:745)
29-3-15 19:54:41.723 | NotificationLis | NotifyThread   | INFO : Notification connection down: Socket closed, sleeping 5000ms, then trying a re-connect ...
29-3-15 19:54:41.723 | NotificationLis | NotifyThread   | INFO : Notification listener interrupted.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.syncany.operations.watch.NotificationListener$SocketThread.run(NotificationListener.java:255)
29-3-15 19:54:41.723 | WatchOperation  | WR/yengecHD    | INFO : Stopping notification listener for /home/kudret/yengecHD ...
29-3-15 19:54:41.724 | NotificationLis | WR/yengecHD    | INFO : Stopping notification listener thread ...
29-3-15 19:54:41.724 | NotificationLis | NotifyThread   | INFO : STOPPED notification listener!
29-3-15 19:54:41.724 | WatchOperation  | WR/yengecHD    | INFO : Stopping recursive watcher for /home/kudret/yengecHD ...
29-3-15 19:54:41.724 | NotificationLis | NotifyThread   | INFO : Notification connection down: Socket closed, sleeping 5000ms, then trying a re-connect ...
29-3-15 19:54:41.724 | NotificationLis | NotifyThread   | INFO : Notification listener interrupted.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.syncany.operations.watch.NotificationListener$SocketThread.run(NotificationListener.java:255)
29-3-15 19:54:41.724 | NotificationLis | NotifyThread   | INFO : STOPPED notification listener!
29-3-15 19:54:42.759 | GuiOperation    | Thread-4       | INFO : SHUTDOWN of daemon complete.
29-3-15 19:58:16.354 | WatchRunner     | WR/piHD        | INFO : STOPPED watch at /home/kudret/piHD
29-3-15 20:01:02.137 | WatchRunner     | WR/yengecHD    | INFO : STOPPED watch at /home/kudret/yengecHD
29-3-15 20:01:05.131 | WatchRunner     | WR/ntck        | INFO : STOPPED watch at /home/kudret/ntck

**Comment by Kudret** [comment]
Sorry for not being clear. From the error message I understand that there is no changes to the current state of the daemon. It was tried to be stopped, however this attempt failed, so we are back to square one.

The logs though, clearly state that somethings were stopped. So I was puzzled:
state a - daemon is running
state b - daemon was attempted to be stopped but attempt failed

what state are we now? state a or some state between a and b?
