### ISSUE TITLE
sy down fails with 'database down?'

### ISSUE THREAD

**Issue by Kudret** [syncany/syncany#436]
kudret@fin:~/piHD$ sy down -d
debug
Application version: 0.4.4-alpha
9-4-15 22:57:43.769 | CommandLineClie | main           | INFO : Application version: 0.4.4-alpha
9-4-15 22:57:43.792 | org.syncany.plu | main           | FINE : Validating required fields
9-4-15 22:57:43.804 | org.syncany.plu | main           | FINE : Validating required fields
9-4-15 22:57:43.809 | DatabaseConnect | main           | INFO : Loading database driver org.hsqldb.jdbcDriver ...
FATAL [hsqldb.db.HSQLDB4B52F25C47.ENGINE] /home/kudret/piHD/.syncany/db/local.db.data getFromFile out of mem 62168008
java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.lib.StringConverter.readUTF(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readString(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readChar(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinaryDecode.readData(Unknown Source)
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.setAccessor(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
FATAL [hsqldb.db.HSQLDB4B52F25C47.ENGINE] /home/kudret/piHD/.syncany/db/local.db.data getFromFile out of mem 62168008
java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.lib.StringConverter.readUTF(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readString(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readChar(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinaryDecode.readData(Unknown Source)
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.setAccessor(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
FATAL [hsqldb.db.HSQLDB4B52F25C47.ENGINE] /home/kudret/piHD/.syncany/db/local.db.data getFromFile failed 62168008
org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.setAccessor(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:127)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:84)
	at org.syncany.config.Config.createDatabaseConnection(Config.java:237)
	at org.syncany.database.SqlDatabase.<init>(SqlDatabase.java:75)
	at org.syncany.operations.down.DownOperation.<init>(DownOperation.java:112)
	at org.syncany.Client.down(Client.java:128)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.lib.StringConverter.readUTF(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readString(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readChar(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinaryDecode.readData(Unknown Source)
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.setAccessor(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
 WARN [hsqldb.db.HSQLDB4B52F25C47.ENGINE] java.lang.OutOfMemoryError: Java heap space in statement [SET TABLE PUBLIC.DATABASEVERSION INDEX '62168008 62156928 62168008 62156928 0 0 0 0 53']
org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.setAccessor(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:127)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:84)
	at org.syncany.config.Config.createDatabaseConnection(Config.java:237)
	at org.syncany.database.SqlDatabase.<init>(SqlDatabase.java:75)
	at org.syncany.operations.down.DownOperation.<init>(DownOperation.java:112)
	at org.syncany.Client.down(Client.java:128)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.lib.StringConverter.readUTF(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readString(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readChar(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinaryDecode.readData(Unknown Source)
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.setAccessor(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
 WARN [hsqldb.db.HSQLDB4B52F25C47.ENGINE] Script processing failure
org.hsqldb.HsqlException: error in script file line: /home/kudret/piHD/.syncany/db/local.db 65
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:127)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:84)
	at org.syncany.config.Config.createDatabaseConnection(Config.java:237)
	at org.syncany.database.SqlDatabase.<init>(SqlDatabase.java:75)
	at org.syncany.operations.down.DownOperation.<init>(DownOperation.java:112)
	at org.syncany.Client.down(Client.java:128)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.setAccessor(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	... 25 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.lib.StringConverter.readUTF(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readString(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readChar(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinaryDecode.readData(Unknown Source)
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.setAccessor(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
FATAL [hsqldb.db.HSQLDB4B52F25C47.ENGINE] could not reopen database
org.hsqldb.HsqlException: error in script file line: /home/kudret/piHD/.syncany/db/local.db 65
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:127)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:84)
	at org.syncany.config.Config.createDatabaseConnection(Config.java:237)
	at org.syncany.database.SqlDatabase.<init>(SqlDatabase.java:75)
	at org.syncany.operations.down.DownOperation.<init>(DownOperation.java:112)
	at org.syncany.Client.down(Client.java:128)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.setAccessor(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	... 25 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.lib.StringConverter.readUTF(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readString(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readChar(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinaryDecode.readData(Unknown Source)
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.setAccessor(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
9-4-15 22:57:44.504 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DownCommand@1b5cd69c FAILED. 
java.lang.RuntimeException: Cannot create new connection; database down?
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:147)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:84)
	at org.syncany.config.Config.createDatabaseConnection(Config.java:237)
	at org.syncany.database.SqlDatabase.<init>(SqlDatabase.java:75)
	at org.syncany.operations.down.DownOperation.<init>(DownOperation.java:112)
	at org.syncany.Client.down(Client.java:128)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: java.sql.SQLException: error in script file line: /home/kudret/piHD/.syncany/db/local.db 65
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:127)
	... 10 more
Caused by: org.hsqldb.HsqlException: error in script file line: /home/kudret/piHD/.syncany/db/local.db 65
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	... 16 more
Caused by: org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.setAccessor(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	... 25 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.lib.StringConverter.readUTF(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readString(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readChar(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBase.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readData(Unknown Source)
	at org.hsqldb.rowio.RowInputBinaryDecode.readData(Unknown Source)
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.setAccessor(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.Table.setIndexRoots(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
Error: Cannot create new connection; database down?
       Refer to help page using '--help'.

kudret@fin:~/piHD$

**Comment by pimotte** [comment]
Given how this the folder name suggests that this is a raspberry Pi, and the JVM runs out of memory while reading the database, this suggests that the metadata from a single client, or maybe the whole repo, consumes more memory than that you have available.

This could possibly be resolved by: #364 (work pending at #396 and the branch feature/issue364-pim, which is this PR with some of my modifications).

Another thing that could resolve this is smarter loading of databaseversions. 

For me, the memory issues have the second highest priority (after data integrity bugs).

I'm afraid I can't think of any workaround at the moment, I'll get back to you if I end up doing so.

**Comment by Kudret** [comment]
Don't mind me. The other two clients are working just fine. So, nothing urgent on this side. I'll report what happens after next release.

**Comment by binwiederhier** [comment]
Next release is here. Any updates?

**Comment by Kudret** [comment]
Sorry, already deleted the directory as well as that large repository. Keeping small now but I'll ping you if I see anything similar.

**Comment by pimotte** [comment]
We've made a lot of memory related improvements recently, and these will be in a release shortly. If you run into this again, feel free to reopen this or make a new issue.
