### ISSUE TITLE
sync down fails with: java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by Asherehsa** [syncany/syncany#442]
debug
Application version: 0.4.4-alpha
...
16-4-15 13:07:26.743 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DownCommand@52a95fa3 FAILED. 
java.io.IOException: java.util.zip.ZipException: error in opening zip file
	at org.syncany.chunk.ZipMultiChunker.createMultiChunk(ZipMultiChunker.java:53)
	at org.syncany.operations.Assembler.assembleToCache(Assembler.java:114)
	at org.syncany.operations.down.actions.FileCreatingFileSystemAction.assembleFileToCache(FileCreatingFileSystemAction.java:82)
	at org.syncany.operations.down.actions.FileCreatingFileSystemAction.createFile(FileCreatingFileSystemAction.java:74)
	at org.syncany.operations.down.actions.FileCreatingFileSystemAction.createFileFolderOrSymlink(FileCreatingFileSystemAction.java:38)
	at org.syncany.operations.down.actions.NewFileSystemAction.execute(NewFileSystemAction.java:42)
	at org.syncany.operations.down.ApplyChangesOperation.applyFileSystemActions(ApplyChangesOperation.java:194)
	at org.syncany.operations.down.ApplyChangesOperation.execute(ApplyChangesOperation.java:103)
	at org.syncany.operations.down.DownOperation.applyWinnersBranch(DownOperation.java:457)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:189)
	at org.syncany.Client.down(Client.java:128)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.zip.ZipFile.<init>(ZipFile.java:159)
	at org.syncany.chunk.ZipMultiChunk.<init>(ZipMultiChunk.java:50)
	at org.syncany.chunk.ZipMultiChunker.createMultiChunk(ZipMultiChunker.java:50)
	... 15 more
Error: java.util.zip.ZipException: error in opening zip file
       Refer to help page using '--help'.

**Comment by pimotte** [comment]
Can you give some more details, like: What is your storage medium/plugin? Is it conceivable the multichunk was altered in any way? Can you reproduce this starting from a clean repo?

**Comment by Asherehsa** [comment]
it was the webdav plugin syncing to box.com. I'll try deleting this repo and reconnecting.

**Comment by Asherehsa** [comment]
Just deleting and reconnecting fixed it!
