### ISSUE TITLE
syncany do not support localdir created by a gvfs/fuse mountpoint

### ISSUE THREAD

**Issue by betaglop** [syncany/syncany#482]
Why the library used by syncany seems to not like the complex paths ?... we have here a localdir that is distant webdav "briefcase" mounted locally (through gvfs/fuse) and we cannot work inside ... here is the debug log from syncany :

$ sy -ddd down
Error: /run/user/1111/gvfs/dav:host=zimbra,ssl=true,prefix=%2Fdav%2Fjojo/Briefcase/syncany/.syncany/logs/syncany.log.0 (Operation not supported)
       Refer to help page using '--help'.

What is really disappointing is that if we mount again this complex directory path on another directory using a fuse "bindfs" mount, it fails again, but in a different way :+1: 

$ sy -ddd down
debug
Application version: 0.4.5-alpha
2-6-15 15:59:53.603 | CommandLineClie | main           | INFO : Application version: 0.4.5-alpha
2-6-15 15:59:54.887 | org.syncany.plu | main           | FINE : Validating required fields
2-6-15 15:59:55.063 | TransferManager | main           | INFO : Building LocalTransferManager from config 'syncany' ...
2-6-15 15:59:55.407 | TransferManager | main           | INFO : - With feature Retriable
2-6-15 15:59:55.408 | TransferManager | main           | FINE : - Checking if selected features supported ...
2-6-15 15:59:55.413 | TransferManager | main           | FINE : - Checking for duplicate features ...
2-6-15 15:59:55.416 | TransferManager | main           | FINE : - Checking required feature TransactionAware in LocalTransferManager ...
2-6-15 15:59:55.421 | TransferManager | main           | FINE : - Checking required feature Retriable in LocalTransferManager ...
2-6-15 15:59:55.424 | TransferManager | main           | FINE : - Wrapping TransferManager LocalTransferManager in RetriableFeatureTransferManager
2-6-15 15:59:55.426 | org.syncany.plu | main           | FINE : Validating required fields
2-6-15 15:59:55.428 | TransferManager | main           | INFO : Building LocalTransferManager from config 'syncany' ...
2-6-15 15:59:55.429 | TransferManager | main           | INFO : - With feature Retriable
2-6-15 15:59:55.430 | TransferManager | main           | INFO : - With feature PathAware
2-6-15 15:59:55.431 | TransferManager | main           | INFO : - With feature TransactionAware
2-6-15 15:59:55.434 | TransferManager | main           | FINE : - Checking if selected features supported ...
2-6-15 15:59:55.435 | TransferManager | main           | FINE : - Checking for duplicate features ...
2-6-15 15:59:55.436 | TransferManager | main           | FINE : - Checking required feature TransactionAware in LocalTransferManager ...
2-6-15 15:59:55.436 | TransferManager | main           | FINE : - Checking required feature Retriable in LocalTransferManager ...
2-6-15 15:59:55.437 | TransferManager | main           | FINE : - Wrapping TransferManager LocalTransferManager in RetriableFeatureTransferManager
2-6-15 15:59:55.438 | TransferManager | main           | INFO : - SKIPPING unsupported optional feature PathAware
2-6-15 15:59:55.439 | TransferManager | main           | FINE : - Wrapping TransferManager RetriableFeatureTransferManager in TransactionAwareFeatureTransferManager
2-6-15 15:59:55.446 | DatabaseConnect | main           | INFO : Loading database driver org.hsqldb.jdbcDriver ...
2-6-15 16:00:00.200 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DownCommand@7a407909 FAILED. 
java.lang.RuntimeException: Another process is using the database.
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:144)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:84)
	at org.syncany.config.Config.createDatabaseConnection(Config.java:237)
	at org.syncany.database.SqlDatabase.<init>(SqlDatabase.java:75)
	at org.syncany.operations.down.DownOperation.<init>(DownOperation.java:112)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
	at org.syncany.Syncany.main(Syncany.java:52)
Caused by: java.sql.SQLException: Database lock acquisition failure: lockFile: org.hsqldb.persist.LockFile@20572d91[file =/home/beta/tmp/syncany/.syncany/db/local.db.lck, exists=true, locked=false, valid=false, ] method: openRAF reason: java.io.FileNotFoundException: /home/beta/tmp/syncany/.syncany/db/local.db.lck (No such file or directory)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:127)
	... 9 more
Caused by: org.hsqldb.HsqlException: Database lock acquisition failure: lockFile: org.hsqldb.persist.LockFile@20572d91[file =/home/beta/tmp/syncany/.syncany/db/local.db.lck, exists=true, locked=false, valid=false, ] method: openRAF reason: java.io.FileNotFoundException: /home/beta/tmp/syncany/.syncany/db/local.db.lck (No such file or directory)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.LockFile.newLockFileLock(Unknown Source)
	at org.hsqldb.persist.Logger.acquireLock(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	... 15 more
Error: Another process is using the database.
       Refer to help page using '--help'.

Thanks in advance for your attention,

**Comment by betaglop** [comment]
note that a workaround would be to use wdfs (https://github.com/jmesmon/wdfs) in it latest revision... but this does not resolv the issue described above.
