### ISSUE TITLE
Could not generate DH 4096 bits keypair

### ISSUE THREAD

**Issue by oparoz** [syncany/syncany#483]
While trying to connect to my ownCloud server, I only get this in the logs.

```
3-6-15 20:52:26.256 | WebdavTransferM | IntRq/Sample p | INFO : WebDAV: isTrusted([Ljava.security.cert.X509Certificate;@3ae1b9ca, DHE_RSA)
3-6-15 20:52:26.258 | WebdavTransferM | IntRq/Sample p | WARN : testRepoFileExists: Exception thrown while testing if repo file exists.
javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:823)
	at com.github.sardine.impl.SardineImpl.exists(SardineImpl.java:804)
	at org.syncany.plugins.webdav.WebdavTransferManager.testRepoFileExists(WebdavTransferManager.java:384)
	at org.syncany.plugins.transfer.AbstractTransferManager.test(AbstractTransferManager.java:84)
	at org.syncany.operations.init.InitOperation.performRepoTest(InitOperation.java:194)
	at org.syncany.operations.init.InitOperation.execute(InitOperation.java:92)
	at org.syncany.operations.daemon.messages.InitManagementRequestHandler$1.run(InitManagementRequestHandler.java:44)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Could not generate DH keypair
	at sun.security.ssl.DHCrypt.<init>(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverKeyExchange(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	... 23 more
Caused by: java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 2048 (inclusive)
	at com.sun.crypto.provider.DHKeyPairGenerator.initialize(DHKeyPairGenerator.java:120)
	at java.security.KeyPairGenerator$Delegate.initialize(Unknown Source)
	... 30 more
```

The ownCloud client can connect, no problem.

Here is the list of supported ciphers
```
prio  ciphersuite                  protocols              pfs_keysize
1     DHE-RSA-AES256-GCM-SHA384    TLSv1.2                DH,4096bits
2     DHE-RSA-AES256-SHA256        TLSv1.2                DH,4096bits
3     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2                ECDH,B-571,570bits
4     ECDHE-RSA-AES256-SHA384      TLSv1.2                ECDH,B-571,570bits
5     DHE-RSA-AES128-GCM-SHA256    TLSv1.2                DH,4096bits
6     DHE-RSA-AES128-SHA256        TLSv1.2                DH,4096bits
7     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2                ECDH,B-571,570bits
8     ECDHE-RSA-AES128-SHA256      TLSv1.2                ECDH,B-571,570bits
9     ECDHE-RSA-RC4-SHA            TLSv1,TLSv1.1,TLSv1.2  ECDH,B-571,570bits
10    DHE-RSA-CAMELLIA256-SHA      TLSv1,TLSv1.1,TLSv1.2  DH,4096bits
11    DHE-RSA-AES256-SHA           TLSv1,TLSv1.1,TLSv1.2  DH,4096bits
12    ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,B-571,570bits
13    DHE-RSA-CAMELLIA128-SHA      TLSv1,TLSv1.1,TLSv1.2  DH,4096bits
14    DHE-RSA-AES128-SHA           TLSv1,TLSv1.1,TLSv1.2  DH,4096bits
15    ECDHE-RSA-AES128-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,B-571,570bits
```

**Comment by pimotte** [comment]
Which version of Owncloud are you running?

**Comment by oparoz** [comment]
I've tried with both 8.0 and 8.1.
I have no idea if it used to work as it's the first time trying Syncany.

In the ownCloud log, I get an exception about missing auth headers, but that's probably a side effect of the Exception on the client side.

Regarding the DH parameters, I have been using those for years and I think I've been using the ownCloud client since ownCloud 6. I know Java is quite picky about what it can accept as DH parameters, but I guess I've never needed to connect any Java app to this server before.

**Comment by pimotte** [comment]
Well, if you can configure ownCloud to use parameters that Java likes that would be preferable. Otherwise I'll try to reproduce this in about a week or two.

**Comment by oparoz** [comment]
It seems like the only solution is to downgrade to 2048bit as Java is not capable of trying the next key length. It just throws an exception.

I think there are 2 things which can be done from your side:
1. Print an error message in the client, so that users know what's going on. Without looking at the logs, I was about to open a totally different issue about missing auth headers
2. Add something to the FAQ so that users know what to do in case of failure

**Comment by binwiederhier** [comment]
Seems like Java's JCE can only handle 1024-bit keys for DH as per http://stackoverflow.com/a/6852095/1440785

"The problem is the prime size. The maximum-acceptable size that Java accepts is 1024 bits. This is a known issue (see JDK-6521495). The bug report that I linked to mentions a workaround using BouncyCastle's JCE implementation. Hopefully that should work for you."

Since this is a Sardine library issue, I hardly think we can do anything about that programmatically. 

The bug report (and its duplicates) also suggests that this has been fixed in Java 8. Can you confirm this? Also, have you enabled "unlimited strength"? It should be done automatically by our code, but I'm not sure we've tested it (or have unit tests for it)...

See
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7044060

Please let us know. Otherwise I'd like to close this as it is unfortunately not something we can influence/fix ...

**Comment by oparoz** [comment]
Java8 can use DH2048, but nothing higher, so yes, you can close this. Would still be good to add something to the FAQ since this will disappear. Error 502 in the test connection isn't giving enough information to fix the problem.

**Comment by binwiederhier** [comment]
Here you go. http://syncany.readthedocs.org/en/latest/faq.html#error-message-could-not-generate-dh-4096-bits-keypair

Hereby closed

**Comment by oparoz** [comment]
Except that upgrading to Java 8 doesn't fix the issue with 4096 bits DH keys.
2048 bits keys -> upgrade to Java 8 
4096 bits keys -> downgrade the server's security parameters so that it accepts 2048 bits keys

**Comment by binwiederhier** [comment]
How about that: http://syncany.readthedocs.org/en/latest/faq.html#error-message-could-not-generate-dh-4096-2048-bits-keypair ?

**Comment by oparoz** [comment]
Much better, thank you!
