### ISSUE TITLE
Drops local folder

### ISSUE THREAD

**Issue by interfixus** [syncany/syncany#490]
I run syncany on a desktop and a laptop, both fully updated Debian/Testing. Syncing one small folder via a box.com backend.
Sometimes syncany will forget the local folder. The green tick on the tray icon disappears and the folder is gone from the menu. This may happen at startup, after an hour or two, or not at all.
Exiting syncany, everything looks normal, no java or other process appears to be running. But the problem persist until reboot - I can restart syncany, but the folder and the green tick are still missing.
The 25MB logfile is all about normal housekeeping, except this, which seemes to accompany the error. The samme message is repeated many, many times over, but I shall spare you the megabytes:

21-6-15 10:36:42.907 | GuiWebSocketCli | GuiWsClient    | INFO : Trying to connect to websocket server ...
21-6-15 10:36:42.919 | GuiWebSocketCli | GuiWsClient    | INFO : Starting GUI websocket client with user admin at 127.0.0.1 ...
21-6-15 10:36:42.925 | GuiWebSocketCli | GuiWsClient    | WARN : Web socket connect failure. Waiting, then retrying ...
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.xnio.nio.WorkerThread$ConnectHandle.handleReady(WorkerThread.java:319)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:539)

**Comment by pimotte** [comment]
It seems to be unable to bind to the default port. Can you configure it to bind to a high numbered port that you're sure is not in use and try again? (.config/syncany/daemon.xml)

**Comment by interfixus** [comment]
Will look into that. Strange thing is it's completely intermittent. And Syncany will run for several hours, then suddenly drop everything without apparent reason, and certainly without any ports or firewalls reconfigured.

Yesterday upgraded to snapshot 2015-06-24, which seems to have helped. Still the occasional miss on boot, but now I can just close and restart the gui, and everything's fine (prviously required reboot).

Everythin else is roses. Beautiful software.

**Comment by binwiederhier** [comment]
I can confirm the behavior of one folder vanishing from the UI/daemon. I have not been able to reproduce or find the root cause. But we should leave this open until we do.

**Comment by lisanet** [comment]
I ran into the same problem: I'm quite sure I found the cause of this.
If, after quitting the Syncnc gui, there's still a daemon.pid file in ./config/syncany, Syncing will throw this exception, the next time it is launched. Simply removing the daemon.pid before launching Syncing gui, everything works fine.
You can reliably reproduce this by simply creating a daemon.pid file with some random number in it. Syncing throws the error. Quit Syncany, remove the daemon.pid file, re-lauch Syncany and everything's fine again.

Hope this helps you fix the issue.
