### ISSUE TITLE
integrity constraint violation: unique constraint or index violation; SYS_CT_10097 table: DATABASEVERSION

### ISSUE THREAD

**Issue by akloeber** [syncany/syncany#491]
I get the following error when trying to `sy down`:
```
22-6-15 19:23:48.462 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DownCommand@6639ca2c FAILED. 
java.lang.RuntimeException: Cannot persist database.
	at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:118)
	at org.syncany.database.SqlDatabase.writeDatabaseVersion(SqlDatabase.java:182)
	at org.syncany.operations.down.DownOperation.persistDatabaseVersion(DownOperation.java:602)
	at org.syncany.operations.down.DownOperation.persistDatabaseVersions(DownOperation.java:589)
	at org.syncany.operations.down.DownOperation.applyWinnersBranch(DownOperation.java:469)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:189)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
	at org.syncany.Syncany.main(Syncany.java:52)
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; SYS_CT_10097 table: DATABASEVERSION
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
	at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersionHeaderInternal(DatabaseVersionSqlDao.java:163)
	at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:143)
	at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:108)
	... 10 more
Caused by: org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation; SYS_CT_10097 table: DATABASEVERSION
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Constraint.getException(Unknown Source)
	at org.hsqldb.index.IndexAVL.insert(Unknown Source)
	at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.indexRow(Unknown Source)
	at org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source)
	at org.hsqldb.Session.addInsertAction(Unknown Source)
	at org.hsqldb.Table.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementDML.insertRowSet(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 15 more
Error: Cannot persist database.
       Refer to help page using '--help'.
```
I already removed the local repo and reinitialized it via `sy connect` but the error still occurs (on 2 machines now). So it seams like the database got corrupted.

For full log see: https://gist.github.com/akloeber/edb9d5b54a2b71f0bb42

__Environment:__
Syncany 0.4.5-alpha
Mac OS X 10.10.3

**Comment by pimotte** [comment]
This is a very bad thing.

The problem is that there's a duplicate version of a databaseversion. Can you tell me if anything special happened on 06/20/2015 @ 6:06pm (UTC). Specifically with the computer that has client  HJQmGiotZbCgLkCPuXwB (check logs to find this id). If you have logs from this client (.syncany/logs or .config/syncany/logs), that would be extremely helpful.

The other issue is that there are tons of outdated action files from down operations. How stable is your connection?

**Comment by akloeber** [comment]
There are the logs of 2 machines. Currently I don't have access to the 3rd one:
https://dl.dropboxusercontent.com/u/15830762/logs_0.zip
https://dl.dropboxusercontent.com/u/15830762/logs_1.zip

I can not remember anything special that occurred at that time. I did some back and force while trying to get the daemon to get to work in launchctl (see https://github.com/syncany/syncany/issues/488).

**Comment by akloeber** [comment]
The network connection was pretty stable and I did not do anything special in parallel on both computers. One thing I remember is that I wanted to get rid of some conflicted `.DS_Store` which kept constantly reappearing after deletion although it was present in `.syignore`.

**Comment by pimotte** [comment]
I've located the problem to the fact that apperently two down operations are run at the same time on the same client. (lines 10020/10024 of logs_1/logs/syncany.log.0). Does this folder happen to be present twice in the daemon.xml config on the machine corresponding to logs_1?

If not there is some other reason why we run twice, which should not happen ever.

**Comment by akloeber** [comment]
Well, maybe there have 2 instances been running at the same time when I tried to get the Syncany daemon working in launchctl.
There should be some kind of lock mechanism in place if 2 running instances could corrupt the database.

**Comment by pimotte** [comment]
Mmm, yes, that could have caused it. 

The thing is that the pid-file is our lock mechanism (so that was broken for you). Furthermore, the database of the folder (.syncany/db/) should be locked, so I think it would be impossible for two different processes to work on it at the same time. (But if it were to happen, this is exactly how it would break.)

I'm going to think about this for a bit, but in any case it will be unlikely that we can come to a resolution that keeps your repo functional, so to continue using Syncany, you'll have to create a fresh repo. (If you have space to backup your remote data somewhere, that would be great, if not, I think I have everything I need to work on this)

**Comment by akloeber** [comment]
Ah ok, but if the PID file is part of your lock mechanism its creation and the check for its existence have to be atomic which may be difficult on file level. For the creation you could probably populate a `syncany.pid.tmp` file and rename (i.e. move) it afterwards to `syncany.pid` as on most OS (Linux for sure) moving of a file is atomic. You still have to check other platforms (Windows, Mac). But then you still have to implement an atomic test-and-set ("check for existence, create otherwise and return result") operation on top of that.

There is no problem with the data in my repository. I can just init a new repository and continue as I'm still testing Syncany at this early stage.

**Comment by pimotte** [comment]
Yeah, that was along the lines I was thinking (but much more specific:P). Since you have a good grip on this, it would be very helpful if you could implement it as well;). Of course, if you don't have the time for it we will pick it up. Of all the current issues this is probably about third priority-wise for me.

**Comment by binwiederhier** [comment]
Downgraded the severity of this issue.

**Comment by akloeber** [comment]
@pimotte: I had some time and implemented an abstraction for realizing locks accross several processes (JVMs) based on `java.nio.channels.FileLock` (as suggested in my former comment) including __lots__ of tests. Have a look at https://github.com/akloeber/ip-lock.

You might consider using it in syncany in order to prevent concurrent database access by multiple instances and implement proper locking (either on database or on process level).

**Comment by pimotte** [comment]
Looks cool! Once we get to this we will certainly consider using it.
