### ISSUE TITLE
Linux: daemon won't start after system crash

### ISSUE THREAD

**Issue by schnittchen** [syncany/syncany#493]
```
 ~ ✓ syncany daemon status
Checking daemon: syncanyd not running
 ~ ✓ syncany daemon start
Starting daemon: .......... Failed to start process. EXITING.
Failed command line: $  daemon run
 ~ ✘ syncany daemon run
Error: Syncany daemon already running.
       Refer to help page using '--help'.
```
Also, that's not logical.

**Comment by schnittchen** [comment]
Here's the log output for `suncany daemon start`:

```
25-6-15 0:40:48.719 | PidFileUtil     | main           | INFO : isProcessRunningUnixLike(3219) returned 0, process running = true
25-6-15 0:40:48.725 | DaemonOperation | main           | INFO : Starting daemon operation with action RUN ...
25-6-15 0:40:48.727 | PidFileUtil     | main           | INFO : isProcessRunningUnixLike(3219) returned 0, process running = true
25-6-15 0:40:48.727 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DaemonCommand@1b983bbc FAILED. 
org.syncany.operations.daemon.ServiceAlreadyStartedException: Syncany daemon already running.
        at org.syncany.operations.daemon.DaemonOperation.executeRun(DaemonOperation.java:197)
        at org.syncany.operations.daemon.DaemonOperation.execute(DaemonOperation.java:113)
        at org.syncany.cli.DaemonCommand.execute(DaemonCommand.java:50)
        at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
        at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
        at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
        at org.syncany.Syncany.main(Syncany.java:52)
```

**Comment by schnittchen** [comment]
It turns out I had a process running with the exact same PID as the daemon before the crash.

**Comment by pimotte** [comment]
Thank you for reporting this. I'm going to link this to #491 and close as duplicate, since this one will also be resolved if we use a FileLock on the pid file.

**Comment by schnittchen** [comment]
For posterity (including myself): on linux, the pidfile is at .config/syncany/daemon.pid
