### ISSUE TITLE
Swift: InvocationTargetException due to cleanup-*/database-* files

### ISSUE THREAD

**Issue by mortenpi** [syncany/syncany#501]
Downloading data from the repo using the swift plugin fails with an exception (`sy down` and `sy ls-remote` commands for example).

As an example, with `sy down` I get the following:
```
21-7-15 23:44:22.566 | RetriableFeatur | main           | WARN : Transfer method failed. 1/3 retries. Sleeping 3000ms ...
org.syncany.plugins.transfer.StorageException: java.lang.reflect.InvocationTargetException
        at org.syncany.plugins.transfer.files.RemoteFile.createRemoteFile(RemoteFile.java:130)
        at org.syncany.plugins.swift.SwiftTransferManager.list(SwiftTransferManager.java:208)
        at org.syncany.plugins.transfer.features.RetriableFeatureTransferManager$8.execute(RetriableFeatureTransferManager.java:146)
        at org.syncany.plugins.transfer.features.RetriableFeatureTransferManager.retryMethod(RetriableFeatureTransferManager.java:210)
        at org.syncany.plugins.transfer.features.RetriableFeatureTransferManager.list(RetriableFeatureTransferManager.java:143)
        at org.syncany.plugins.transfer.features.TransactionAwareFeatureTransferManager.list(TransactionAwareFeatureTransferManager.java:148)
        at org.syncany.operations.down.DownOperation.getRemoteCleanupFiles(DownOperation.java:695)
        at org.syncany.operations.down.DownOperation.execute(DownOperation.java:156)
        at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
        at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
        at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
        at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
        at org.syncany.Syncany.main(Syncany.java:52)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.syncany.plugins.transfer.files.RemoteFile.createRemoteFile(RemoteFile.java:127)
        ... 12 more
Caused by: org.syncany.plugins.transfer.StorageException: database-LZeYqizikbLuMEnWGPBK-0000000004: remote filename pattern does not match: cleanup-([0-9]+) expected.
        at org.syncany.plugins.transfer.files.CleanupRemoteFile.validateName(CleanupRemoteFile.java:64)
        at org.syncany.plugins.transfer.files.RemoteFile.<init>(RemoteFile.java:73)
        at org.syncany.plugins.transfer.files.CleanupRemoteFile.<init>(CleanupRemoteFile.java:46)
        ... 17 more
```

The issue seems to be that in [SwiftTransferManager.java:228](https://github.com/syncany/syncany-plugin-swift/blob/develop/src/main/java/org/syncany/plugins/swift/SwiftTransferManager.java#L228) `SwiftTransferManager.getRemoteFilePath()` returns the same `/databases` path for both `cleanup-*` and `database-*` files. `SwiftTransferManager.list()` then gets confused at [SwiftTransferManager.java:212](https://github.com/syncany/syncany-plugin-swift/blob/develop/src/main/java/org/syncany/plugins/swift/SwiftTransferManager.java#L212) since it gets both `cleanup-*` and `database-*` files from the listing, but expects them to be of the specified type.

Versions:
 * Syncany: 0.4.6-alpha (from the deb package)
 * Swift plugin: 0.4.0-alpha from the repos + compiled the develop branch myself

**Comment by cuonic** [comment]
I've got the same problem with the latest Syncthing and Swift plugin. I'll try and look into it.

**Comment by pimotte** [comment]
Please mean Syncany instead of Syncthing:P Or does syncthing implement the Swift API?

I'm pretty sure that in other plugins we just log this as a warning and ignore them. It might be worthwhile to move out the cleanup file into a seperate directory/naming pattern in any case, but I did not really feel like breaking repo compatibility again for all plugins.

**Comment by cuonic** [comment]
Oh geez I'm sorry I did actually mean Syncany, I'm lost in this whole world of Sync apps :P Well this exception makes `sy down` fail completely. I think it's the last big hurdle in getting the Swift plugin to work correctly.
