### ISSUE TITLE
Syncany Swift Plugin: "Unable to create transfer settings: null"

### ISSUE THREAD

**Issue by cuonic** [syncany/syncany#532]
Hi,

I'm trying to use Syncany with OVH's Object Storage (based on OpenStack) so I'm using the Swift plugin. I'm getting the following output when trying to initialize the connection with `sy init`:

    cuonic@cuonicpc ~ $ sy init
    Choose a storage plugin. Available plugins are: local, swift
    Plugin: swift

    Connection details for swift connection:
    - Url to authenticate at the Swift cluster: https://auth.cloud.ovh.net/v2.0
    - Username: MyUsername
    - Password (not displayed): 
    - Target container to use: MyContainer

    Error: Unable to create transfer settings: null
    Refer to help page using '--help'.

This error message comes from [line 74 of `TransferPlugin.java`](https://github.com/syncany/syncany-plugin-swift/blob/develop/core/syncany-lib/src/main/java/org/syncany/plugins/transfer/TransferPlugin.java#L74)

With debug mode:

	cuonic@cuonicpc ~ $ sy -d init
	debug
	Application version: 0.4.7-alpha
	29-11-15 22:41:38.149 | CommandLineClie | main           | INFO : Application version: 0.4.7-alpha
	29-11-15 22:41:38.441 | Plugins         | main           | INFO : - org.syncany.plugins.local.LocalTransferPlugin
	29-11-15 22:41:38.444 | Plugins         | main           | INFO : - org.syncany.plugins.s3.S3TransferPlugin
	29-11-15 22:41:38.446 | Plugins         | main           | INFO : - org.syncany.plugins.swift.SwiftTransferPlugin
	Choose a storage plugin. Available plugins are: local, s3, swift
	Plugin: swift

	Connection details for swift connection:
	- Url to authenticate at the Swift cluster: https://auth.cloud.ovh.net/v2.0/
	- Username: MyUsername
	- Password (not displayed): 
	- Target container to use: MyContainer
	29-11-15 22:42:25.532 | org.syncany.plu | main           | FINE : Validating required fields
	29-11-15 22:42:25.533 | org.syncany.cli | main           | INFO : Settings are SwiftTransferSettings{authUrl=https://auth.cloud.ovh.net/v2.0/, username=MyUsername, password=MyPassword, container=MyContainer}
	29-11-15 22:42:26.052 | AbstractInitOpe | main           | INFO : 
	29-11-15 22:42:26.053 | AbstractInitOpe | main           | INFO : Running 'Init'
	29-11-15 22:42:26.054 | AbstractInitOpe | main           | INFO : --------------------------------------------
	29-11-15 22:42:26.055 | org.syncany.plu | main           | FINE : Validating required fields
	29-11-15 22:42:26.985 | CommandLineClie | main           | SEVE : Command org.syncany.cli.InitCommand@2096442d FAILED. 
	java.lang.RuntimeException: Unable to create transfer settings: null
		at org.syncany.plugins.transfer.TransferPlugin.createTransferManager(TransferPlugin.java:120)
		at org.syncany.operations.init.AbstractInitOperation.createTransferManagerFromNullConfig(AbstractInitOperation.java:127)
		at org.syncany.operations.init.InitOperation.execute(InitOperation.java:79)
		at org.syncany.cli.InitCommand.execute(InitCommand.java:68)
		at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
		at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
		at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
		at org.syncany.Syncany.main(Syncany.java:52)
	Caused by: java.lang.reflect.InvocationTargetException
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
		at org.syncany.plugins.transfer.TransferPlugin.createTransferManager(TransferPlugin.java:117)
		... 7 more
	Caused by: java.lang.NullPointerException
		at org.javaswift.joss.command.impl.identity.AbstractSimpleAuthenticationCommandImpl.getReturnObject(AbstractSimpleAuthenticationCommandImpl.java:33)
		at org.javaswift.joss.command.impl.identity.AbstractSimpleAuthenticationCommandImpl.getReturnObject(AbstractSimpleAuthenticationCommandImpl.java:18)
		at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:51)
		at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:98)
		at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:27)
		at org.javaswift.joss.client.core.AbstractClient.authenticate(AbstractClient.java:35)
		at org.javaswift.joss.client.factory.AccountFactory.createAccount(AccountFactory.java:30)
		at org.syncany.plugins.swift.SwiftTransferManager.<init>(SwiftTransferManager.java:87)
		... 12 more
	Error: Unable to create transfer settings: null
	       Refer to help page using '--help'.

**Comment by cuonic** [comment]
Fixed with https://github.com/syncany/syncany-plugin-swift/pull/3

**Comment by cortopy** [comment]
@cuonic how did you solve it? I'm using 0.4.1-alpha and I can specify Tenant ID, name and region. However, I always get a "HTTP Status code: 400 => UNKNOWN"

**Comment by cuonic** [comment]
@cortopy I had to add `/tokens` to the Auth URL

**Comment by cortopy** [comment]
Thanks @cuonic That did the trick indeed!
