### ISSUE TITLE
Mac OS X GUI hangs on plugin tab

### ISSUE THREAD

**Issue by mrubioroy** [syncany/syncany#537]
When I go to the Preferences->Plugins tab of the Mac OS X GUI and wait for a few seconds, the GUI hangs forever. On the console I see:

	Exception in thread "main" org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
		at org.eclipse.swt.SWT.error(Unknown Source)
		at org.eclipse.swt.SWT.error(Unknown Source)
		at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
		at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
		at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
		at org.syncany.operations.gui.GuiOperation.startEventDispatchLoop(GuiOperation.java:215)
		at org.syncany.operations.gui.GuiOperation.execute(GuiOperation.java:102)
		at org.syncany.cli.GuiCommand.execute(GuiCommand.java:48)
		at org.syncany.cli.GuiCommand.main(GuiCommand.java:40)
	Caused by: java.lang.NullPointerException
		at org.eclipse.swt.widgets.Control.internal_new_GC(Unknown Source)
		at org.eclipse.swt.graphics.GC.cocoa_new(Unknown Source)
		at org.eclipse.swt.widgets.Table.sendMeasureItem(Unknown Source)
		at org.eclipse.swt.widgets.Table.cellSize(Unknown Source)
		at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
		at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper_stret(Native Method)
		at org.eclipse.swt.widgets.Widget.expansionFrameWithFrame_inView(Unknown Source)
		at org.eclipse.swt.widgets.Table.expansionFrameWithFrame_inView(Unknown Source)
		at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
		at org.eclipse.swt.internal.cocoa.OS.objc_msgSend_bool(Native Method)
		at org.eclipse.swt.internal.cocoa.NSRunLoop.runMode(Unknown Source)
		at org.eclipse.swt.widgets.Display.sleep(Unknown Source)
		at org.syncany.gui.preferences.PreferencesDialog.open(PreferencesDialog.java:107)
		at org.syncany.gui.tray.TrayIcon$3.run(TrayIcon.java:174)
		at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
		... 7 more
	7-12-15 21:56:36.023 | UpdateChecker   | UpdateTimer    | INFO : Update check: Not necessary, last check less than 24h ago. Next file check in 60min.

I've just installed Syncany a few days ago. I created a folder synced through the SFTP plugin. I removed this folder and still have the same issue.

Versions: 
Syncany v0.4.7-alpha
Syncany GUI Plugin v0.4.7-alpha
Syncany SFTP Plugin v0.4.5-alpha

**Comment by orgoed** [comment]
Reporting the same issue as mrubioroy.

OS: Mac OS X 10.11.2
Java: 1.8.0_66
