### ISSUE TITLE
"sy down" renders "Error: What to do here?"

### ISSUE THREAD

**Issue by nickk-** [syncany/syncany#558]
System: Windows 8.1 (Version 6.3, Build 9600), ACER Aspire Switch 10 FHD, 2 GB RAM. 
java version "1.8.0_71", Java SE RE (build 1.8.0_71-b15)
Syncany 0.4.7-alpha, using SFTP plugin (snapshot version). 

`D:\syncany\desktopwiki.shared>sy down`
`Downloading database 7/7 ...Error: What to do here?`

I stopped the daemon and went to the CLI to try debugging a problem where sub directories to this directory didn't get synched from/to the machine.

`D:\syncany\desktopwiki.shared>sy up`
`Sync up skipped, because there are remote changes`

**Comment by nickk-** [comment]
So, several hours, one reboot and an ISP (mobile) change later (daemon still off), I tried _sy down_ once again, and this time it worked as expected. 

_sy up_ following the sy down, though, produced the following result:

`D:\syncany\desktopwiki.shared\standardinstanz>sy up`
`Indexing 84 new or altered file(s)...Exception in thread "AsyncI/desktopwiki.shared"` `java.lang.NullPointerException`
`        at org.syncany.operations.up.Indexer.removeDeletedFiles(Indexer.java:178)`
`        at org.syncany.operations.up.Indexer.indexWithNewFiles(Indexer.java:138)`
`        at org.syncany.operations.up.Indexer.index(Indexer.java:116)`
`        at org.syncany.operations.up.AsyncIndexer.run(AsyncIndexer.java:47)`
`        at java.lang.Thread.run(Unknown Source)`

I am quite positive that I didn't change or add that much files in the meantime.

**Comment by pimotte** [comment]
Keep a close eye on whether any files disappear, we had some reports on that and this seems kind of suspect. Could you also make a backup of your logs (.syncany/logs) as they are now?
