### ISSUE TITLE
Cannot connect to ftp (Unable to connect to folder (code: 502))

### ISSUE THREAD

**Issue by jasminder** [syncany/syncany#589]
Hey , 
I am having problem with connecting to my ftp account for syncing the files. 
I am doing it the following way , 
Add Folder > Connect to existing online storage -> Select folder > Connect by manually entering details -> FTP -> Entered details correctly and having following error:

**Connecting to repo for folder C:\Users\ZG\Desktop\jass ...ERROR

Unable to connect to folder (code: 502)
Testing the remote storage failed.

- Was the connection successful: NO
- Files can be created: NO
- Files can be written to: NO
- The target folder/repo exists: NO

Detailed test error:

org.syncany.plugins.transfer.StorageException: java.net.UnknownHostException: ftp.mysite.info

	at org.syncany.plugins.ftp.FtpTransferManager.connect(FtpTransferManager.java:141)

	at org.syncany.plugins.transfer.AbstractTransferManager.test(AbstractTransferManager.java:80)

	at org.syncany.operations.init.ConnectOperation.performRepoTest(ConnectOperation.java:294)

	at org.syncany.operations.init.ConnectOperation.execute(ConnectOperation.java:103)

	at org.syncany.operations.daemon.messages.ConnectManagementRequestHandler$1.run(ConnectManagementRequestHandler.java:44)

	at java.lang.Thread.run(Thread.java:722)

Caused by: java.net.UnknownHostException: ftp.mysite.info

	at java.net.InetAddress.getAllByName0(InetAddress.java:1215)

	at java.net.InetAddress.getAllByName(InetAddress.java:1127)

	at java.net.InetAddress.getAllByName(InetAddress.java:1063)

	at java.net.InetAddress.getByName(InetAddress.java:1013)

	at org.apache.commons.net.SocketClient.connect(SocketClient.java:184)

	at org.syncany.plugins.ftp.FtpTransferManager.connect(FtpTransferManager.java:124)

	... 5 more**

I have tried alot but no luck . The ftp details are correct. 
How can i get it fixed ? Please help

**Comment by jasminder** [comment]
When i try to connect with Web Dav it says this , 
![9c9853214ba739049b1a169962247b34](https://cloud.githubusercontent.com/assets/1322355/15917179/e1071d90-2e17-11e6-9b54-4ce4c218f5ed.png)

I am running syncany as administrator and OS is WIndows 7 64Bit .

**Comment by 5chlueter** [comment]
Hi, same problem to connect to WebDAV. Error 502.
I've looked with wireshark, but I can't see any networktrafic.
