### ISSUE TITLE
I can't download the plugin

### ISSUE THREAD

**Issue by leocGZGZchen** [syncany/syncany#609]
I install the Syncany 0.4.9-alpha in Win10 
when I enter the command **sy plugin install ftp** in CLI, it report the error as follow

**Connecting to api.syncany.org ...Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
       Refer to help page using '--help'.**

how can we slove this problem?

**Comment by westbury** [comment]
I've been getting errors with the certificate chain too.  e.g. below.   Has something in the chain expired?

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.syncany.operations.plugin.PluginOperation.getRemoteListStr(PluginOperation.java:632)
	at org.syncany.operations.plugin.PluginOperation.getRemotePluginInfoList(PluginOperation.java:597)
	at org.syncany.operations.plugin.PluginOperation.executeList(PluginOperation.java:541)
	at org.syncany.operations.plugin.PluginOperation.execute(PluginOperation.java:121)
	at org.syncany.operations.daemon.messages.PluginManagementRequestHandler$1.run(PluginManagementRequestHandler.java:43)
	at java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 25 more

**Comment by binwiederhier** [comment]
I switched from GlobalSSL to Let's Encrypt about 10 days ago or so. That's most likely the cause for this unfortunately.

You may be able to add the Let's Encrypt root cert (which I understand is cross signed by DST, so I don't quite know what Java is complaining about ...) to the standard Java trust store.

Or are you running a very old Java? Check the version here: 
https://letsencrypt.org/docs/certificate-compatibility/

I am travelling right now, so I can't help, but I'll try to switch back to the GlobalSSL cert when I'm back.

**Comment by westbury** [comment]
Yes, that's definitely it.  Java 8 update 72 fails on another HTTPS site using LetsEncrypt but works on other HTTPS sites.  I'm investigating further...

**Comment by westbury** [comment]
Java 8 update 102 works fine.

**Comment by cr0** [comment]
Solved
