### ISSUE TITLE
Indexing failed.

### ISSUE THREAD

**Issue by benjamingrogg** [syncany/syncany#614]
Since few days I cant sync anymore to S3.

benny@E6420:~/Cloud/AmazonS3$ **sy up**
Indexing 52 new or altered file(s)...Exception in thread "AsyncI/AmazonS3" java.lang.NullPointerException
	at org.syncany.operations.up.Indexer.removeDeletedFiles(Indexer.java:178)
	at org.syncany.operations.up.Indexer.indexWithNewFiles(Indexer.java:138)
	at org.syncany.operations.up.Indexer.index(Indexer.java:116)
	at org.syncany.operations.up.AsyncIndexer.run(AsyncIndexer.java:47)
	at java.lang.Thread.run(Thread.java:748)
                 
^Cbenny@E6420:~/Cloud/AmazonS3$ **sy up --no-resume**
Indexing 52 new or altered file(s)...Exception in thread "AsyncI/AmazonS3" java.lang.NullPointerException
	at org.syncany.operations.up.Indexer.removeDeletedFiles(Indexer.java:178)
	at org.syncany.operations.up.Indexer.indexWithNewFiles(Indexer.java:138)
	at org.syncany.operations.up.Indexer.index(Indexer.java:116)
	at org.syncany.operations.up.AsyncIndexer.run(AsyncIndexer.java:47)
	at java.lang.Thread.run(Thread.java:748)

Syncany 0.4.9-alpha and S3 Plugin with version 0.4.6-alpha

Recently I got a Java update

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

Any hints? Many thanks for your input!
benny

**Comment by pimotte** [comment]
Can you run `syncany up --no-resume -d` and post the log? (Or mail it to
team@syncany.org)

**Comment by benjamingrogg** [comment]
[syncany_log.txt](https://github.com/syncany/syncany/files/1015224/syncany_log.txt)
Hi pimotte

Many thanks for your fast answer. See attachment for full log.

Best regards,
benny

**Comment by benjamingrogg** [comment]
After a while it stuck in a loop 
[syncany_log2.txt](https://github.com/syncany/syncany/files/1015254/syncany_log2.txt)
