### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter when generating secret key On Ubuntu 19.10

### ISSUE THREAD

**Issue by yohaoquan** [syncany/syncany#635]
I am new to the whole ubuntu environment so am unsure what else I should provide other than the stack trace. Please inform if more information is needed.

myuser@mydoman:~# sy
First launch, creating a secret key (could take a sec)...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at org.syncany.util.StringUtil.toHex(StringUtil.java:105)
	at org.syncany.crypto.SaltedSecretKeyConverter.write(SaltedSecretKeyConverter.java:42)
	at org.syncany.crypto.SaltedSecretKeyConverter.write(SaltedSecretKeyConverter.java:33)
	at org.simpleframework.xml.convert.AnnotationStrategy.write(AnnotationStrategy.java:180)
	at org.simpleframework.xml.convert.AnnotationStrategy.write(AnnotationStrategy.java:156)
	at org.simpleframework.xml.core.Source.setOverride(Source.java:384)
	at org.simpleframework.xml.core.Factory.setOverride(Factory.java:170)
	at org.simpleframework.xml.core.Composite.isOverridden(Composite.java:1312)
	at org.simpleframework.xml.core.Composite.writeElement(Composite.java:1234)
	at org.simpleframework.xml.core.Composite.writeUnion(Composite.java:1127)
	at org.simpleframework.xml.core.Composite.writeElements(Composite.java:1098)
	at org.simpleframework.xml.core.Composite.writeSection(Composite.java:1004)
	at org.simpleframework.xml.core.Composite.write(Composite.java:975)
	at org.simpleframework.xml.core.Composite.write(Composite.java:952)
	at org.simpleframework.xml.core.Traverser.write(Traverser.java:236)
	at org.simpleframework.xml.core.Traverser.write(Traverser.java:208)
	at org.simpleframework.xml.core.Traverser.write(Traverser.java:186)
	at org.simpleframework.xml.core.Persister.write(Persister.java:1180)
	at org.simpleframework.xml.core.Persister.write(Persister.java:1162)
	at org.simpleframework.xml.core.Persister.write(Persister.java:1140)
	at org.simpleframework.xml.core.Persister.write(Persister.java:1259)
	at org.simpleframework.xml.core.Persister.write(Persister.java:1241)
	at org.simpleframework.xml.core.Persister.write(Persister.java:1222)
	at org.simpleframework.xml.core.Persister.write(Persister.java:1201)
	at org.syncany.config.to.UserConfigTO.save(UserConfigTO.java:92)
	at org.syncany.config.UserConfig.writeExampleUserConfigFile(UserConfig.java:205)
	at org.syncany.config.UserConfig.initUserConfig(UserConfig.java:171)
	at org.syncany.config.UserConfig.init(UserConfig.java:86)
	at org.syncany.config.UserConfig.<clinit>(UserConfig.java:80)
	at org.syncany.Client.initUserConfig(Client.java:92)
	at org.syncany.Client.<clinit>(Client.java:54)
	at org.syncany.Syncany.main(Syncany.java:52)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 32 more

**Comment by pimotte** [comment]
Looks like we're using some functionality that got split out in recent
versions of Java. You could try running it with version 11. My guess is
you're on 14 now?

**Comment by MaxenceG2M** [comment]
Hi!

I have the same issue with java 14.
I'm on a WSL environment.

I try with an OpenJDK version 11, with same issue.
[EDIT] I try with another environment, same issue :(.

Tried with: 
```
$ java --version
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```
and 

```$ java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
```

Alway same stack trace, see below.

Maybe it's because I'm in a WSL environment.
I will try in a native Linux soon.

```
# me@mycomputer:~
$ sy --help
First launch, creating a secret key (could take a sec)...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at org.syncany.util.StringUtil.toHex(StringUtil.java:105)
        at org.syncany.crypto.SaltedSecretKeyConverter.write(SaltedSecretKeyConverter.java:42)
        at org.syncany.crypto.SaltedSecretKeyConverter.write(SaltedSecretKeyConverter.java:33)
        at org.simpleframework.xml.convert.AnnotationStrategy.write(AnnotationStrategy.java:180)
        at org.simpleframework.xml.convert.AnnotationStrategy.write(AnnotationStrategy.java:156)
        at org.simpleframework.xml.core.Source.setOverride(Source.java:384)
        at org.simpleframework.xml.core.Factory.setOverride(Factory.java:170)
        at org.simpleframework.xml.core.Composite.isOverridden(Composite.java:1312)
        at org.simpleframework.xml.core.Composite.writeElement(Composite.java:1234)
        at org.simpleframework.xml.core.Composite.writeUnion(Composite.java:1127)
        at org.simpleframework.xml.core.Composite.writeElements(Composite.java:1098)
        at org.simpleframework.xml.core.Composite.writeSection(Composite.java:1004)
        at org.simpleframework.xml.core.Composite.write(Composite.java:975)
        at org.simpleframework.xml.core.Composite.write(Composite.java:952)
        at org.simpleframework.xml.core.Traverser.write(Traverser.java:236)
        at org.simpleframework.xml.core.Traverser.write(Traverser.java:208)
        at org.simpleframework.xml.core.Traverser.write(Traverser.java:186)
        at org.simpleframework.xml.core.Persister.write(Persister.java:1180)
        at org.simpleframework.xml.core.Persister.write(Persister.java:1162)
        at org.simpleframework.xml.core.Persister.write(Persister.java:1140)
        at org.simpleframework.xml.core.Persister.write(Persister.java:1259)
        at org.simpleframework.xml.core.Persister.write(Persister.java:1241)
        at org.simpleframework.xml.core.Persister.write(Persister.java:1222)
        at org.simpleframework.xml.core.Persister.write(Persister.java:1201)
        at org.syncany.config.to.UserConfigTO.save(UserConfigTO.java:92)
        at org.syncany.config.UserConfig.writeExampleUserConfigFile(UserConfig.java:205)
        at org.syncany.config.UserConfig.initUserConfig(UserConfig.java:171)
        at org.syncany.config.UserConfig.init(UserConfig.java:86)
        at org.syncany.config.UserConfig.<clinit>(UserConfig.java:80)
        at org.syncany.Client.initUserConfig(Client.java:92)
        at org.syncany.Client.<clinit>(Client.java:54)
        at org.syncany.Syncany.main(Syncany.java:52)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 32 more
```
